// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: account/v1/account.proto

#include "account/v1/account.pb.h"
#include "account/v1/account.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace account {
namespace v1 {

static const char* AccountService_method_names[] = {
  "/account.v1.AccountService/ListEmailAddresses",
  "/account.v1.AccountService/CreateAccount",
  "/account.v1.AccountService/ListAccountById",
  "/account.v1.AccountService/ListAccounts",
  "/account.v1.AccountService/UpdateAccount",
  "/account.v1.AccountService/DeleteAccount",
  "/account.v1.AccountService/FetchPassword",
  "/account.v1.AccountService/ChangePassword",
};

std::unique_ptr< AccountService::Stub> AccountService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AccountService::Stub> stub(new AccountService::Stub(channel, options));
  return stub;
}

AccountService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListEmailAddresses_(AccountService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateAccount_(AccountService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListAccountById_(AccountService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListAccounts_(AccountService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateAccount_(AccountService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteAccount_(AccountService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FetchPassword_(AccountService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ChangePassword_(AccountService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AccountService::Stub::ListEmailAddresses(::grpc::ClientContext* context, const ::account::v1::ListEmailAddressesReq& request, ::account::v1::ListEmailAddressesResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::ListEmailAddressesReq, ::account::v1::ListEmailAddressesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListEmailAddresses_, context, request, response);
}

void AccountService::Stub::async::ListEmailAddresses(::grpc::ClientContext* context, const ::account::v1::ListEmailAddressesReq* request, ::account::v1::ListEmailAddressesResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::ListEmailAddressesReq, ::account::v1::ListEmailAddressesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListEmailAddresses_, context, request, response, std::move(f));
}

void AccountService::Stub::async::ListEmailAddresses(::grpc::ClientContext* context, const ::account::v1::ListEmailAddressesReq* request, ::account::v1::ListEmailAddressesResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListEmailAddresses_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListEmailAddressesResp>* AccountService::Stub::PrepareAsyncListEmailAddressesRaw(::grpc::ClientContext* context, const ::account::v1::ListEmailAddressesReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::ListEmailAddressesResp, ::account::v1::ListEmailAddressesReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListEmailAddresses_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListEmailAddressesResp>* AccountService::Stub::AsyncListEmailAddressesRaw(::grpc::ClientContext* context, const ::account::v1::ListEmailAddressesReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListEmailAddressesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AccountService::Stub::CreateAccount(::grpc::ClientContext* context, const ::account::v1::CreateAccountReq& request, ::account::v1::CreateAccountResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::CreateAccountReq, ::account::v1::CreateAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateAccount_, context, request, response);
}

void AccountService::Stub::async::CreateAccount(::grpc::ClientContext* context, const ::account::v1::CreateAccountReq* request, ::account::v1::CreateAccountResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::CreateAccountReq, ::account::v1::CreateAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAccount_, context, request, response, std::move(f));
}

void AccountService::Stub::async::CreateAccount(::grpc::ClientContext* context, const ::account::v1::CreateAccountReq* request, ::account::v1::CreateAccountResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::CreateAccountResp>* AccountService::Stub::PrepareAsyncCreateAccountRaw(::grpc::ClientContext* context, const ::account::v1::CreateAccountReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::CreateAccountResp, ::account::v1::CreateAccountReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::CreateAccountResp>* AccountService::Stub::AsyncCreateAccountRaw(::grpc::ClientContext* context, const ::account::v1::CreateAccountReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AccountService::Stub::ListAccountById(::grpc::ClientContext* context, const ::account::v1::ListAccountByIdReq& request, ::account::v1::ListAccountByIdResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::ListAccountByIdReq, ::account::v1::ListAccountByIdResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListAccountById_, context, request, response);
}

void AccountService::Stub::async::ListAccountById(::grpc::ClientContext* context, const ::account::v1::ListAccountByIdReq* request, ::account::v1::ListAccountByIdResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::ListAccountByIdReq, ::account::v1::ListAccountByIdResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAccountById_, context, request, response, std::move(f));
}

void AccountService::Stub::async::ListAccountById(::grpc::ClientContext* context, const ::account::v1::ListAccountByIdReq* request, ::account::v1::ListAccountByIdResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAccountById_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListAccountByIdResp>* AccountService::Stub::PrepareAsyncListAccountByIdRaw(::grpc::ClientContext* context, const ::account::v1::ListAccountByIdReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::ListAccountByIdResp, ::account::v1::ListAccountByIdReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListAccountById_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListAccountByIdResp>* AccountService::Stub::AsyncListAccountByIdRaw(::grpc::ClientContext* context, const ::account::v1::ListAccountByIdReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListAccountByIdRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AccountService::Stub::ListAccounts(::grpc::ClientContext* context, const ::account::v1::ListAccountsReq& request, ::account::v1::ListAccountsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::ListAccountsReq, ::account::v1::ListAccountsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListAccounts_, context, request, response);
}

void AccountService::Stub::async::ListAccounts(::grpc::ClientContext* context, const ::account::v1::ListAccountsReq* request, ::account::v1::ListAccountsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::ListAccountsReq, ::account::v1::ListAccountsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAccounts_, context, request, response, std::move(f));
}

void AccountService::Stub::async::ListAccounts(::grpc::ClientContext* context, const ::account::v1::ListAccountsReq* request, ::account::v1::ListAccountsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAccounts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListAccountsResp>* AccountService::Stub::PrepareAsyncListAccountsRaw(::grpc::ClientContext* context, const ::account::v1::ListAccountsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::ListAccountsResp, ::account::v1::ListAccountsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListAccounts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListAccountsResp>* AccountService::Stub::AsyncListAccountsRaw(::grpc::ClientContext* context, const ::account::v1::ListAccountsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListAccountsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AccountService::Stub::UpdateAccount(::grpc::ClientContext* context, const ::account::v1::UpdateAccountReq& request, ::account::v1::UpdateAccountResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::UpdateAccountReq, ::account::v1::UpdateAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateAccount_, context, request, response);
}

void AccountService::Stub::async::UpdateAccount(::grpc::ClientContext* context, const ::account::v1::UpdateAccountReq* request, ::account::v1::UpdateAccountResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::UpdateAccountReq, ::account::v1::UpdateAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateAccount_, context, request, response, std::move(f));
}

void AccountService::Stub::async::UpdateAccount(::grpc::ClientContext* context, const ::account::v1::UpdateAccountReq* request, ::account::v1::UpdateAccountResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::UpdateAccountResp>* AccountService::Stub::PrepareAsyncUpdateAccountRaw(::grpc::ClientContext* context, const ::account::v1::UpdateAccountReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::UpdateAccountResp, ::account::v1::UpdateAccountReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::UpdateAccountResp>* AccountService::Stub::AsyncUpdateAccountRaw(::grpc::ClientContext* context, const ::account::v1::UpdateAccountReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AccountService::Stub::DeleteAccount(::grpc::ClientContext* context, const ::account::v1::DeleteAccountReq& request, ::account::v1::DeleteAccountResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::DeleteAccountReq, ::account::v1::DeleteAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteAccount_, context, request, response);
}

void AccountService::Stub::async::DeleteAccount(::grpc::ClientContext* context, const ::account::v1::DeleteAccountReq* request, ::account::v1::DeleteAccountResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::DeleteAccountReq, ::account::v1::DeleteAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAccount_, context, request, response, std::move(f));
}

void AccountService::Stub::async::DeleteAccount(::grpc::ClientContext* context, const ::account::v1::DeleteAccountReq* request, ::account::v1::DeleteAccountResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::DeleteAccountResp>* AccountService::Stub::PrepareAsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::account::v1::DeleteAccountReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::DeleteAccountResp, ::account::v1::DeleteAccountReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::DeleteAccountResp>* AccountService::Stub::AsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::account::v1::DeleteAccountReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AccountService::Stub::FetchPassword(::grpc::ClientContext* context, const ::account::v1::FetchPasswordReq& request, ::account::v1::FetchPasswordResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::FetchPasswordReq, ::account::v1::FetchPasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FetchPassword_, context, request, response);
}

void AccountService::Stub::async::FetchPassword(::grpc::ClientContext* context, const ::account::v1::FetchPasswordReq* request, ::account::v1::FetchPasswordResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::FetchPasswordReq, ::account::v1::FetchPasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchPassword_, context, request, response, std::move(f));
}

void AccountService::Stub::async::FetchPassword(::grpc::ClientContext* context, const ::account::v1::FetchPasswordReq* request, ::account::v1::FetchPasswordResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchPassword_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::FetchPasswordResp>* AccountService::Stub::PrepareAsyncFetchPasswordRaw(::grpc::ClientContext* context, const ::account::v1::FetchPasswordReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::FetchPasswordResp, ::account::v1::FetchPasswordReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FetchPassword_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::FetchPasswordResp>* AccountService::Stub::AsyncFetchPasswordRaw(::grpc::ClientContext* context, const ::account::v1::FetchPasswordReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFetchPasswordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AccountService::Stub::ChangePassword(::grpc::ClientContext* context, const ::account::v1::ChangePasswordReq& request, ::account::v1::ChangePasswordResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::ChangePasswordReq, ::account::v1::ChangePasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ChangePassword_, context, request, response);
}

void AccountService::Stub::async::ChangePassword(::grpc::ClientContext* context, const ::account::v1::ChangePasswordReq* request, ::account::v1::ChangePasswordResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::ChangePasswordReq, ::account::v1::ChangePasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ChangePassword_, context, request, response, std::move(f));
}

void AccountService::Stub::async::ChangePassword(::grpc::ClientContext* context, const ::account::v1::ChangePasswordReq* request, ::account::v1::ChangePasswordResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ChangePassword_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ChangePasswordResp>* AccountService::Stub::PrepareAsyncChangePasswordRaw(::grpc::ClientContext* context, const ::account::v1::ChangePasswordReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::ChangePasswordResp, ::account::v1::ChangePasswordReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ChangePassword_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ChangePasswordResp>* AccountService::Stub::AsyncChangePasswordRaw(::grpc::ClientContext* context, const ::account::v1::ChangePasswordReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncChangePasswordRaw(context, request, cq);
  result->StartCall();
  return result;
}

AccountService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccountService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccountService::Service, ::account::v1::ListEmailAddressesReq, ::account::v1::ListEmailAddressesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::ListEmailAddressesReq* req,
             ::account::v1::ListEmailAddressesResp* resp) {
               return service->ListEmailAddresses(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccountService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccountService::Service, ::account::v1::CreateAccountReq, ::account::v1::CreateAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::CreateAccountReq* req,
             ::account::v1::CreateAccountResp* resp) {
               return service->CreateAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccountService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccountService::Service, ::account::v1::ListAccountByIdReq, ::account::v1::ListAccountByIdResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::ListAccountByIdReq* req,
             ::account::v1::ListAccountByIdResp* resp) {
               return service->ListAccountById(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccountService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccountService::Service, ::account::v1::ListAccountsReq, ::account::v1::ListAccountsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::ListAccountsReq* req,
             ::account::v1::ListAccountsResp* resp) {
               return service->ListAccounts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccountService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccountService::Service, ::account::v1::UpdateAccountReq, ::account::v1::UpdateAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::UpdateAccountReq* req,
             ::account::v1::UpdateAccountResp* resp) {
               return service->UpdateAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccountService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccountService::Service, ::account::v1::DeleteAccountReq, ::account::v1::DeleteAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::DeleteAccountReq* req,
             ::account::v1::DeleteAccountResp* resp) {
               return service->DeleteAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccountService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccountService::Service, ::account::v1::FetchPasswordReq, ::account::v1::FetchPasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::FetchPasswordReq* req,
             ::account::v1::FetchPasswordResp* resp) {
               return service->FetchPassword(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccountService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccountService::Service, ::account::v1::ChangePasswordReq, ::account::v1::ChangePasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AccountService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::ChangePasswordReq* req,
             ::account::v1::ChangePasswordResp* resp) {
               return service->ChangePassword(ctx, req, resp);
             }, this)));
}

AccountService::Service::~Service() {
}

::grpc::Status AccountService::Service::ListEmailAddresses(::grpc::ServerContext* context, const ::account::v1::ListEmailAddressesReq* request, ::account::v1::ListEmailAddressesResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AccountService::Service::CreateAccount(::grpc::ServerContext* context, const ::account::v1::CreateAccountReq* request, ::account::v1::CreateAccountResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AccountService::Service::ListAccountById(::grpc::ServerContext* context, const ::account::v1::ListAccountByIdReq* request, ::account::v1::ListAccountByIdResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AccountService::Service::ListAccounts(::grpc::ServerContext* context, const ::account::v1::ListAccountsReq* request, ::account::v1::ListAccountsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AccountService::Service::UpdateAccount(::grpc::ServerContext* context, const ::account::v1::UpdateAccountReq* request, ::account::v1::UpdateAccountResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AccountService::Service::DeleteAccount(::grpc::ServerContext* context, const ::account::v1::DeleteAccountReq* request, ::account::v1::DeleteAccountResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AccountService::Service::FetchPassword(::grpc::ServerContext* context, const ::account::v1::FetchPasswordReq* request, ::account::v1::FetchPasswordResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AccountService::Service::ChangePassword(::grpc::ServerContext* context, const ::account::v1::ChangePasswordReq* request, ::account::v1::ChangePasswordResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace account
}  // namespace v1

