// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: account/v1/category.proto

#include "account/v1/category.pb.h"
#include "account/v1/category.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace account {
namespace v1 {

static const char* CategoryService_method_names[] = {
  "/account.v1.CategoryService/CreateCategory",
  "/account.v1.CategoryService/ListNameOfCategories",
  "/account.v1.CategoryService/ListCategories",
  "/account.v1.CategoryService/UpdateCategories",
  "/account.v1.CategoryService/DeleteCategories",
};

std::unique_ptr< CategoryService::Stub> CategoryService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CategoryService::Stub> stub(new CategoryService::Stub(channel, options));
  return stub;
}

CategoryService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateCategory_(CategoryService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListNameOfCategories_(CategoryService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListCategories_(CategoryService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateCategories_(CategoryService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteCategories_(CategoryService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CategoryService::Stub::CreateCategory(::grpc::ClientContext* context, const ::account::v1::CreateCategoryReq& request, ::account::v1::CreateCategoryResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::CreateCategoryReq, ::account::v1::CreateCategoryResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateCategory_, context, request, response);
}

void CategoryService::Stub::async::CreateCategory(::grpc::ClientContext* context, const ::account::v1::CreateCategoryReq* request, ::account::v1::CreateCategoryResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::CreateCategoryReq, ::account::v1::CreateCategoryResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCategory_, context, request, response, std::move(f));
}

void CategoryService::Stub::async::CreateCategory(::grpc::ClientContext* context, const ::account::v1::CreateCategoryReq* request, ::account::v1::CreateCategoryResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCategory_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::CreateCategoryResp>* CategoryService::Stub::PrepareAsyncCreateCategoryRaw(::grpc::ClientContext* context, const ::account::v1::CreateCategoryReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::CreateCategoryResp, ::account::v1::CreateCategoryReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateCategory_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::CreateCategoryResp>* CategoryService::Stub::AsyncCreateCategoryRaw(::grpc::ClientContext* context, const ::account::v1::CreateCategoryReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateCategoryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CategoryService::Stub::ListNameOfCategories(::grpc::ClientContext* context, const ::account::v1::ListNameOfCategoriesReq& request, ::account::v1::ListNameOfCategoriesResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::ListNameOfCategoriesReq, ::account::v1::ListNameOfCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListNameOfCategories_, context, request, response);
}

void CategoryService::Stub::async::ListNameOfCategories(::grpc::ClientContext* context, const ::account::v1::ListNameOfCategoriesReq* request, ::account::v1::ListNameOfCategoriesResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::ListNameOfCategoriesReq, ::account::v1::ListNameOfCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListNameOfCategories_, context, request, response, std::move(f));
}

void CategoryService::Stub::async::ListNameOfCategories(::grpc::ClientContext* context, const ::account::v1::ListNameOfCategoriesReq* request, ::account::v1::ListNameOfCategoriesResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListNameOfCategories_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListNameOfCategoriesResp>* CategoryService::Stub::PrepareAsyncListNameOfCategoriesRaw(::grpc::ClientContext* context, const ::account::v1::ListNameOfCategoriesReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::ListNameOfCategoriesResp, ::account::v1::ListNameOfCategoriesReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListNameOfCategories_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListNameOfCategoriesResp>* CategoryService::Stub::AsyncListNameOfCategoriesRaw(::grpc::ClientContext* context, const ::account::v1::ListNameOfCategoriesReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListNameOfCategoriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CategoryService::Stub::ListCategories(::grpc::ClientContext* context, const ::account::v1::ListCategoriesReq& request, ::account::v1::ListCategoriesResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::ListCategoriesReq, ::account::v1::ListCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListCategories_, context, request, response);
}

void CategoryService::Stub::async::ListCategories(::grpc::ClientContext* context, const ::account::v1::ListCategoriesReq* request, ::account::v1::ListCategoriesResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::ListCategoriesReq, ::account::v1::ListCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListCategories_, context, request, response, std::move(f));
}

void CategoryService::Stub::async::ListCategories(::grpc::ClientContext* context, const ::account::v1::ListCategoriesReq* request, ::account::v1::ListCategoriesResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListCategories_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListCategoriesResp>* CategoryService::Stub::PrepareAsyncListCategoriesRaw(::grpc::ClientContext* context, const ::account::v1::ListCategoriesReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::ListCategoriesResp, ::account::v1::ListCategoriesReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListCategories_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListCategoriesResp>* CategoryService::Stub::AsyncListCategoriesRaw(::grpc::ClientContext* context, const ::account::v1::ListCategoriesReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListCategoriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CategoryService::Stub::UpdateCategories(::grpc::ClientContext* context, const ::account::v1::UpdateCategoriesReq& request, ::account::v1::UpdateCategoriesResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::UpdateCategoriesReq, ::account::v1::UpdateCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateCategories_, context, request, response);
}

void CategoryService::Stub::async::UpdateCategories(::grpc::ClientContext* context, const ::account::v1::UpdateCategoriesReq* request, ::account::v1::UpdateCategoriesResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::UpdateCategoriesReq, ::account::v1::UpdateCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateCategories_, context, request, response, std::move(f));
}

void CategoryService::Stub::async::UpdateCategories(::grpc::ClientContext* context, const ::account::v1::UpdateCategoriesReq* request, ::account::v1::UpdateCategoriesResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateCategories_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::UpdateCategoriesResp>* CategoryService::Stub::PrepareAsyncUpdateCategoriesRaw(::grpc::ClientContext* context, const ::account::v1::UpdateCategoriesReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::UpdateCategoriesResp, ::account::v1::UpdateCategoriesReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateCategories_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::UpdateCategoriesResp>* CategoryService::Stub::AsyncUpdateCategoriesRaw(::grpc::ClientContext* context, const ::account::v1::UpdateCategoriesReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateCategoriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CategoryService::Stub::DeleteCategories(::grpc::ClientContext* context, const ::account::v1::DeleteCategoriesReq& request, ::account::v1::DeleteCategoriesResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::DeleteCategoriesReq, ::account::v1::DeleteCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteCategories_, context, request, response);
}

void CategoryService::Stub::async::DeleteCategories(::grpc::ClientContext* context, const ::account::v1::DeleteCategoriesReq* request, ::account::v1::DeleteCategoriesResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::DeleteCategoriesReq, ::account::v1::DeleteCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteCategories_, context, request, response, std::move(f));
}

void CategoryService::Stub::async::DeleteCategories(::grpc::ClientContext* context, const ::account::v1::DeleteCategoriesReq* request, ::account::v1::DeleteCategoriesResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteCategories_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::DeleteCategoriesResp>* CategoryService::Stub::PrepareAsyncDeleteCategoriesRaw(::grpc::ClientContext* context, const ::account::v1::DeleteCategoriesReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::DeleteCategoriesResp, ::account::v1::DeleteCategoriesReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteCategories_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::DeleteCategoriesResp>* CategoryService::Stub::AsyncDeleteCategoriesRaw(::grpc::ClientContext* context, const ::account::v1::DeleteCategoriesReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteCategoriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

CategoryService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CategoryService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CategoryService::Service, ::account::v1::CreateCategoryReq, ::account::v1::CreateCategoryResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CategoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::CreateCategoryReq* req,
             ::account::v1::CreateCategoryResp* resp) {
               return service->CreateCategory(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CategoryService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CategoryService::Service, ::account::v1::ListNameOfCategoriesReq, ::account::v1::ListNameOfCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CategoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::ListNameOfCategoriesReq* req,
             ::account::v1::ListNameOfCategoriesResp* resp) {
               return service->ListNameOfCategories(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CategoryService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CategoryService::Service, ::account::v1::ListCategoriesReq, ::account::v1::ListCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CategoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::ListCategoriesReq* req,
             ::account::v1::ListCategoriesResp* resp) {
               return service->ListCategories(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CategoryService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CategoryService::Service, ::account::v1::UpdateCategoriesReq, ::account::v1::UpdateCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CategoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::UpdateCategoriesReq* req,
             ::account::v1::UpdateCategoriesResp* resp) {
               return service->UpdateCategories(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CategoryService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CategoryService::Service, ::account::v1::DeleteCategoriesReq, ::account::v1::DeleteCategoriesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CategoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::DeleteCategoriesReq* req,
             ::account::v1::DeleteCategoriesResp* resp) {
               return service->DeleteCategories(ctx, req, resp);
             }, this)));
}

CategoryService::Service::~Service() {
}

::grpc::Status CategoryService::Service::CreateCategory(::grpc::ServerContext* context, const ::account::v1::CreateCategoryReq* request, ::account::v1::CreateCategoryResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CategoryService::Service::ListNameOfCategories(::grpc::ServerContext* context, const ::account::v1::ListNameOfCategoriesReq* request, ::account::v1::ListNameOfCategoriesResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CategoryService::Service::ListCategories(::grpc::ServerContext* context, const ::account::v1::ListCategoriesReq* request, ::account::v1::ListCategoriesResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CategoryService::Service::UpdateCategories(::grpc::ServerContext* context, const ::account::v1::UpdateCategoriesReq* request, ::account::v1::UpdateCategoriesResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CategoryService::Service::DeleteCategories(::grpc::ServerContext* context, const ::account::v1::DeleteCategoriesReq* request, ::account::v1::DeleteCategoriesResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace account
}  // namespace v1

