// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: account/v1/phone.proto
#ifndef GRPC_account_2fv1_2fphone_2eproto__INCLUDED
#define GRPC_account_2fv1_2fphone_2eproto__INCLUDED

#include "account/v1/phone.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace account {
namespace v1 {

class PhoneService final {
 public:
  static constexpr char const* service_full_name() {
    return "account.v1.PhoneService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::account::v1::CreatePhoneResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::CreatePhoneResp>> AsyncCreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::CreatePhoneResp>>(AsyncCreatePhoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::CreatePhoneResp>> PrepareAsyncCreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::CreatePhoneResp>>(PrepareAsyncCreatePhoneRaw(context, request, cq));
    }
    virtual ::grpc::Status ListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::account::v1::ListPhoneNumbersResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneNumbersResp>> AsyncListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneNumbersResp>>(AsyncListPhoneNumbersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneNumbersResp>> PrepareAsyncListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneNumbersResp>>(PrepareAsyncListPhoneNumbersRaw(context, request, cq));
    }
    virtual ::grpc::Status ListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::account::v1::ListPhoneResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneResp>> AsyncListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneResp>>(AsyncListPhoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneResp>> PrepareAsyncListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneResp>>(PrepareAsyncListPhoneRaw(context, request, cq));
    }
    virtual ::grpc::Status FindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::account::v1::FindPhoneByIdResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::FindPhoneByIdResp>> AsyncFindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::FindPhoneByIdResp>>(AsyncFindPhoneByIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::FindPhoneByIdResp>> PrepareAsyncFindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::FindPhoneByIdResp>>(PrepareAsyncFindPhoneByIdRaw(context, request, cq));
    }
    virtual ::grpc::Status UpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::account::v1::UpdatePhoneResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::UpdatePhoneResp>> AsyncUpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::UpdatePhoneResp>>(AsyncUpdatePhoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::UpdatePhoneResp>> PrepareAsyncUpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::UpdatePhoneResp>>(PrepareAsyncUpdatePhoneRaw(context, request, cq));
    }
    virtual ::grpc::Status DeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::account::v1::DeletePhoneResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::DeletePhoneResp>> AsyncDeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::DeletePhoneResp>>(AsyncDeletePhoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::DeletePhoneResp>> PrepareAsyncDeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::DeletePhoneResp>>(PrepareAsyncDeletePhoneRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq* request, ::account::v1::CreatePhoneResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq* request, ::account::v1::CreatePhoneResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq* request, ::account::v1::ListPhoneNumbersResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq* request, ::account::v1::ListPhoneNumbersResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq* request, ::account::v1::ListPhoneResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq* request, ::account::v1::ListPhoneResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq* request, ::account::v1::FindPhoneByIdResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq* request, ::account::v1::FindPhoneByIdResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void UpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq* request, ::account::v1::UpdatePhoneResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq* request, ::account::v1::UpdatePhoneResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq* request, ::account::v1::DeletePhoneResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq* request, ::account::v1::DeletePhoneResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::CreatePhoneResp>* AsyncCreatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::CreatePhoneResp>* PrepareAsyncCreatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneNumbersResp>* AsyncListPhoneNumbersRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneNumbersResp>* PrepareAsyncListPhoneNumbersRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneResp>* AsyncListPhoneRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListPhoneResp>* PrepareAsyncListPhoneRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::FindPhoneByIdResp>* AsyncFindPhoneByIdRaw(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::FindPhoneByIdResp>* PrepareAsyncFindPhoneByIdRaw(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::UpdatePhoneResp>* AsyncUpdatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::UpdatePhoneResp>* PrepareAsyncUpdatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::DeletePhoneResp>* AsyncDeletePhoneRaw(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::DeletePhoneResp>* PrepareAsyncDeletePhoneRaw(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::account::v1::CreatePhoneResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::CreatePhoneResp>> AsyncCreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::CreatePhoneResp>>(AsyncCreatePhoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::CreatePhoneResp>> PrepareAsyncCreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::CreatePhoneResp>>(PrepareAsyncCreatePhoneRaw(context, request, cq));
    }
    ::grpc::Status ListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::account::v1::ListPhoneNumbersResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneNumbersResp>> AsyncListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneNumbersResp>>(AsyncListPhoneNumbersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneNumbersResp>> PrepareAsyncListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneNumbersResp>>(PrepareAsyncListPhoneNumbersRaw(context, request, cq));
    }
    ::grpc::Status ListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::account::v1::ListPhoneResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneResp>> AsyncListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneResp>>(AsyncListPhoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneResp>> PrepareAsyncListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneResp>>(PrepareAsyncListPhoneRaw(context, request, cq));
    }
    ::grpc::Status FindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::account::v1::FindPhoneByIdResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::FindPhoneByIdResp>> AsyncFindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::FindPhoneByIdResp>>(AsyncFindPhoneByIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::FindPhoneByIdResp>> PrepareAsyncFindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::FindPhoneByIdResp>>(PrepareAsyncFindPhoneByIdRaw(context, request, cq));
    }
    ::grpc::Status UpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::account::v1::UpdatePhoneResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::UpdatePhoneResp>> AsyncUpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::UpdatePhoneResp>>(AsyncUpdatePhoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::UpdatePhoneResp>> PrepareAsyncUpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::UpdatePhoneResp>>(PrepareAsyncUpdatePhoneRaw(context, request, cq));
    }
    ::grpc::Status DeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::account::v1::DeletePhoneResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::DeletePhoneResp>> AsyncDeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::DeletePhoneResp>>(AsyncDeletePhoneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::DeletePhoneResp>> PrepareAsyncDeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::DeletePhoneResp>>(PrepareAsyncDeletePhoneRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq* request, ::account::v1::CreatePhoneResp* response, std::function<void(::grpc::Status)>) override;
      void CreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq* request, ::account::v1::CreatePhoneResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq* request, ::account::v1::ListPhoneNumbersResp* response, std::function<void(::grpc::Status)>) override;
      void ListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq* request, ::account::v1::ListPhoneNumbersResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq* request, ::account::v1::ListPhoneResp* response, std::function<void(::grpc::Status)>) override;
      void ListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq* request, ::account::v1::ListPhoneResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq* request, ::account::v1::FindPhoneByIdResp* response, std::function<void(::grpc::Status)>) override;
      void FindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq* request, ::account::v1::FindPhoneByIdResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq* request, ::account::v1::UpdatePhoneResp* response, std::function<void(::grpc::Status)>) override;
      void UpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq* request, ::account::v1::UpdatePhoneResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq* request, ::account::v1::DeletePhoneResp* response, std::function<void(::grpc::Status)>) override;
      void DeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq* request, ::account::v1::DeletePhoneResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::account::v1::CreatePhoneResp>* AsyncCreatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::CreatePhoneResp>* PrepareAsyncCreatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneNumbersResp>* AsyncListPhoneNumbersRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneNumbersResp>* PrepareAsyncListPhoneNumbersRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneResp>* AsyncListPhoneRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneResp>* PrepareAsyncListPhoneRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::FindPhoneByIdResp>* AsyncFindPhoneByIdRaw(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::FindPhoneByIdResp>* PrepareAsyncFindPhoneByIdRaw(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::UpdatePhoneResp>* AsyncUpdatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::UpdatePhoneResp>* PrepareAsyncUpdatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::DeletePhoneResp>* AsyncDeletePhoneRaw(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::DeletePhoneResp>* PrepareAsyncDeletePhoneRaw(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreatePhone_;
    const ::grpc::internal::RpcMethod rpcmethod_ListPhoneNumbers_;
    const ::grpc::internal::RpcMethod rpcmethod_ListPhone_;
    const ::grpc::internal::RpcMethod rpcmethod_FindPhoneById_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdatePhone_;
    const ::grpc::internal::RpcMethod rpcmethod_DeletePhone_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreatePhone(::grpc::ServerContext* context, const ::account::v1::CreatePhoneReq* request, ::account::v1::CreatePhoneResp* response);
    virtual ::grpc::Status ListPhoneNumbers(::grpc::ServerContext* context, const ::account::v1::ListPhoneNumbersReq* request, ::account::v1::ListPhoneNumbersResp* response);
    virtual ::grpc::Status ListPhone(::grpc::ServerContext* context, const ::account::v1::ListPhoneReq* request, ::account::v1::ListPhoneResp* response);
    virtual ::grpc::Status FindPhoneById(::grpc::ServerContext* context, const ::account::v1::FindPhoneByIdReq* request, ::account::v1::FindPhoneByIdResp* response);
    virtual ::grpc::Status UpdatePhone(::grpc::ServerContext* context, const ::account::v1::UpdatePhoneReq* request, ::account::v1::UpdatePhoneResp* response);
    virtual ::grpc::Status DeletePhone(::grpc::ServerContext* context, const ::account::v1::DeletePhoneReq* request, ::account::v1::DeletePhoneResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreatePhone() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::CreatePhoneReq* /*request*/, ::account::v1::CreatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreatePhone(::grpc::ServerContext* context, ::account::v1::CreatePhoneReq* request, ::grpc::ServerAsyncResponseWriter< ::account::v1::CreatePhoneResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListPhoneNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListPhoneNumbers() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListPhoneNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhoneNumbers(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneNumbersReq* /*request*/, ::account::v1::ListPhoneNumbersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListPhoneNumbers(::grpc::ServerContext* context, ::account::v1::ListPhoneNumbersReq* request, ::grpc::ServerAsyncResponseWriter< ::account::v1::ListPhoneNumbersResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListPhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListPhone() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ListPhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhone(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneReq* /*request*/, ::account::v1::ListPhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListPhone(::grpc::ServerContext* context, ::account::v1::ListPhoneReq* request, ::grpc::ServerAsyncResponseWriter< ::account::v1::ListPhoneResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FindPhoneById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FindPhoneById() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_FindPhoneById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindPhoneById(::grpc::ServerContext* /*context*/, const ::account::v1::FindPhoneByIdReq* /*request*/, ::account::v1::FindPhoneByIdResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindPhoneById(::grpc::ServerContext* context, ::account::v1::FindPhoneByIdReq* request, ::grpc::ServerAsyncResponseWriter< ::account::v1::FindPhoneByIdResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdatePhone() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_UpdatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::UpdatePhoneReq* /*request*/, ::account::v1::UpdatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdatePhone(::grpc::ServerContext* context, ::account::v1::UpdatePhoneReq* request, ::grpc::ServerAsyncResponseWriter< ::account::v1::UpdatePhoneResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeletePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeletePhone() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_DeletePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePhone(::grpc::ServerContext* /*context*/, const ::account::v1::DeletePhoneReq* /*request*/, ::account::v1::DeletePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeletePhone(::grpc::ServerContext* context, ::account::v1::DeletePhoneReq* request, ::grpc::ServerAsyncResponseWriter< ::account::v1::DeletePhoneResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreatePhone<WithAsyncMethod_ListPhoneNumbers<WithAsyncMethod_ListPhone<WithAsyncMethod_FindPhoneById<WithAsyncMethod_UpdatePhone<WithAsyncMethod_DeletePhone<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreatePhone() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::account::v1::CreatePhoneReq, ::account::v1::CreatePhoneResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::v1::CreatePhoneReq* request, ::account::v1::CreatePhoneResp* response) { return this->CreatePhone(context, request, response); }));}
    void SetMessageAllocatorFor_CreatePhone(
        ::grpc::MessageAllocator< ::account::v1::CreatePhoneReq, ::account::v1::CreatePhoneResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::v1::CreatePhoneReq, ::account::v1::CreatePhoneResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::CreatePhoneReq* /*request*/, ::account::v1::CreatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreatePhone(
      ::grpc::CallbackServerContext* /*context*/, const ::account::v1::CreatePhoneReq* /*request*/, ::account::v1::CreatePhoneResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListPhoneNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListPhoneNumbers() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::account::v1::ListPhoneNumbersReq, ::account::v1::ListPhoneNumbersResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::v1::ListPhoneNumbersReq* request, ::account::v1::ListPhoneNumbersResp* response) { return this->ListPhoneNumbers(context, request, response); }));}
    void SetMessageAllocatorFor_ListPhoneNumbers(
        ::grpc::MessageAllocator< ::account::v1::ListPhoneNumbersReq, ::account::v1::ListPhoneNumbersResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::v1::ListPhoneNumbersReq, ::account::v1::ListPhoneNumbersResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListPhoneNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhoneNumbers(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneNumbersReq* /*request*/, ::account::v1::ListPhoneNumbersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListPhoneNumbers(
      ::grpc::CallbackServerContext* /*context*/, const ::account::v1::ListPhoneNumbersReq* /*request*/, ::account::v1::ListPhoneNumbersResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListPhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListPhone() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::account::v1::ListPhoneReq, ::account::v1::ListPhoneResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::v1::ListPhoneReq* request, ::account::v1::ListPhoneResp* response) { return this->ListPhone(context, request, response); }));}
    void SetMessageAllocatorFor_ListPhone(
        ::grpc::MessageAllocator< ::account::v1::ListPhoneReq, ::account::v1::ListPhoneResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::v1::ListPhoneReq, ::account::v1::ListPhoneResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListPhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhone(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneReq* /*request*/, ::account::v1::ListPhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListPhone(
      ::grpc::CallbackServerContext* /*context*/, const ::account::v1::ListPhoneReq* /*request*/, ::account::v1::ListPhoneResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FindPhoneById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FindPhoneById() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::account::v1::FindPhoneByIdReq, ::account::v1::FindPhoneByIdResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::v1::FindPhoneByIdReq* request, ::account::v1::FindPhoneByIdResp* response) { return this->FindPhoneById(context, request, response); }));}
    void SetMessageAllocatorFor_FindPhoneById(
        ::grpc::MessageAllocator< ::account::v1::FindPhoneByIdReq, ::account::v1::FindPhoneByIdResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::v1::FindPhoneByIdReq, ::account::v1::FindPhoneByIdResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FindPhoneById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindPhoneById(::grpc::ServerContext* /*context*/, const ::account::v1::FindPhoneByIdReq* /*request*/, ::account::v1::FindPhoneByIdResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FindPhoneById(
      ::grpc::CallbackServerContext* /*context*/, const ::account::v1::FindPhoneByIdReq* /*request*/, ::account::v1::FindPhoneByIdResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdatePhone() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::account::v1::UpdatePhoneReq, ::account::v1::UpdatePhoneResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::v1::UpdatePhoneReq* request, ::account::v1::UpdatePhoneResp* response) { return this->UpdatePhone(context, request, response); }));}
    void SetMessageAllocatorFor_UpdatePhone(
        ::grpc::MessageAllocator< ::account::v1::UpdatePhoneReq, ::account::v1::UpdatePhoneResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::v1::UpdatePhoneReq, ::account::v1::UpdatePhoneResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::UpdatePhoneReq* /*request*/, ::account::v1::UpdatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdatePhone(
      ::grpc::CallbackServerContext* /*context*/, const ::account::v1::UpdatePhoneReq* /*request*/, ::account::v1::UpdatePhoneResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeletePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeletePhone() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::account::v1::DeletePhoneReq, ::account::v1::DeletePhoneResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::v1::DeletePhoneReq* request, ::account::v1::DeletePhoneResp* response) { return this->DeletePhone(context, request, response); }));}
    void SetMessageAllocatorFor_DeletePhone(
        ::grpc::MessageAllocator< ::account::v1::DeletePhoneReq, ::account::v1::DeletePhoneResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::v1::DeletePhoneReq, ::account::v1::DeletePhoneResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeletePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePhone(::grpc::ServerContext* /*context*/, const ::account::v1::DeletePhoneReq* /*request*/, ::account::v1::DeletePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeletePhone(
      ::grpc::CallbackServerContext* /*context*/, const ::account::v1::DeletePhoneReq* /*request*/, ::account::v1::DeletePhoneResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreatePhone<WithCallbackMethod_ListPhoneNumbers<WithCallbackMethod_ListPhone<WithCallbackMethod_FindPhoneById<WithCallbackMethod_UpdatePhone<WithCallbackMethod_DeletePhone<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreatePhone() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::CreatePhoneReq* /*request*/, ::account::v1::CreatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListPhoneNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListPhoneNumbers() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListPhoneNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhoneNumbers(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneNumbersReq* /*request*/, ::account::v1::ListPhoneNumbersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListPhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListPhone() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ListPhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhone(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneReq* /*request*/, ::account::v1::ListPhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FindPhoneById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FindPhoneById() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_FindPhoneById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindPhoneById(::grpc::ServerContext* /*context*/, const ::account::v1::FindPhoneByIdReq* /*request*/, ::account::v1::FindPhoneByIdResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdatePhone() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_UpdatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::UpdatePhoneReq* /*request*/, ::account::v1::UpdatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeletePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeletePhone() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_DeletePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePhone(::grpc::ServerContext* /*context*/, const ::account::v1::DeletePhoneReq* /*request*/, ::account::v1::DeletePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreatePhone() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::CreatePhoneReq* /*request*/, ::account::v1::CreatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreatePhone(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListPhoneNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListPhoneNumbers() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListPhoneNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhoneNumbers(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneNumbersReq* /*request*/, ::account::v1::ListPhoneNumbersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListPhoneNumbers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListPhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListPhone() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ListPhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhone(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneReq* /*request*/, ::account::v1::ListPhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListPhone(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FindPhoneById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FindPhoneById() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_FindPhoneById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindPhoneById(::grpc::ServerContext* /*context*/, const ::account::v1::FindPhoneByIdReq* /*request*/, ::account::v1::FindPhoneByIdResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindPhoneById(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdatePhone() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_UpdatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::UpdatePhoneReq* /*request*/, ::account::v1::UpdatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdatePhone(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeletePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeletePhone() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_DeletePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePhone(::grpc::ServerContext* /*context*/, const ::account::v1::DeletePhoneReq* /*request*/, ::account::v1::DeletePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeletePhone(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreatePhone() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreatePhone(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::CreatePhoneReq* /*request*/, ::account::v1::CreatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreatePhone(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListPhoneNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListPhoneNumbers() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListPhoneNumbers(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListPhoneNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhoneNumbers(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneNumbersReq* /*request*/, ::account::v1::ListPhoneNumbersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListPhoneNumbers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListPhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListPhone() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListPhone(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListPhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPhone(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneReq* /*request*/, ::account::v1::ListPhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListPhone(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FindPhoneById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FindPhoneById() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FindPhoneById(context, request, response); }));
    }
    ~WithRawCallbackMethod_FindPhoneById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindPhoneById(::grpc::ServerContext* /*context*/, const ::account::v1::FindPhoneByIdReq* /*request*/, ::account::v1::FindPhoneByIdResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FindPhoneById(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdatePhone() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdatePhone(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::UpdatePhoneReq* /*request*/, ::account::v1::UpdatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdatePhone(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeletePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeletePhone() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeletePhone(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeletePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePhone(::grpc::ServerContext* /*context*/, const ::account::v1::DeletePhoneReq* /*request*/, ::account::v1::DeletePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeletePhone(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreatePhone() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::v1::CreatePhoneReq, ::account::v1::CreatePhoneResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::v1::CreatePhoneReq, ::account::v1::CreatePhoneResp>* streamer) {
                       return this->StreamedCreatePhone(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::CreatePhoneReq* /*request*/, ::account::v1::CreatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreatePhone(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::v1::CreatePhoneReq,::account::v1::CreatePhoneResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListPhoneNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListPhoneNumbers() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::v1::ListPhoneNumbersReq, ::account::v1::ListPhoneNumbersResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::v1::ListPhoneNumbersReq, ::account::v1::ListPhoneNumbersResp>* streamer) {
                       return this->StreamedListPhoneNumbers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListPhoneNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListPhoneNumbers(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneNumbersReq* /*request*/, ::account::v1::ListPhoneNumbersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListPhoneNumbers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::v1::ListPhoneNumbersReq,::account::v1::ListPhoneNumbersResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListPhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListPhone() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::v1::ListPhoneReq, ::account::v1::ListPhoneResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::v1::ListPhoneReq, ::account::v1::ListPhoneResp>* streamer) {
                       return this->StreamedListPhone(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListPhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListPhone(::grpc::ServerContext* /*context*/, const ::account::v1::ListPhoneReq* /*request*/, ::account::v1::ListPhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListPhone(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::v1::ListPhoneReq,::account::v1::ListPhoneResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FindPhoneById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FindPhoneById() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::v1::FindPhoneByIdReq, ::account::v1::FindPhoneByIdResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::v1::FindPhoneByIdReq, ::account::v1::FindPhoneByIdResp>* streamer) {
                       return this->StreamedFindPhoneById(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FindPhoneById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FindPhoneById(::grpc::ServerContext* /*context*/, const ::account::v1::FindPhoneByIdReq* /*request*/, ::account::v1::FindPhoneByIdResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFindPhoneById(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::v1::FindPhoneByIdReq,::account::v1::FindPhoneByIdResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdatePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdatePhone() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::v1::UpdatePhoneReq, ::account::v1::UpdatePhoneResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::v1::UpdatePhoneReq, ::account::v1::UpdatePhoneResp>* streamer) {
                       return this->StreamedUpdatePhone(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdatePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdatePhone(::grpc::ServerContext* /*context*/, const ::account::v1::UpdatePhoneReq* /*request*/, ::account::v1::UpdatePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdatePhone(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::v1::UpdatePhoneReq,::account::v1::UpdatePhoneResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeletePhone : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeletePhone() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::v1::DeletePhoneReq, ::account::v1::DeletePhoneResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::v1::DeletePhoneReq, ::account::v1::DeletePhoneResp>* streamer) {
                       return this->StreamedDeletePhone(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeletePhone() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeletePhone(::grpc::ServerContext* /*context*/, const ::account::v1::DeletePhoneReq* /*request*/, ::account::v1::DeletePhoneResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeletePhone(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::v1::DeletePhoneReq,::account::v1::DeletePhoneResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreatePhone<WithStreamedUnaryMethod_ListPhoneNumbers<WithStreamedUnaryMethod_ListPhone<WithStreamedUnaryMethod_FindPhoneById<WithStreamedUnaryMethod_UpdatePhone<WithStreamedUnaryMethod_DeletePhone<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreatePhone<WithStreamedUnaryMethod_ListPhoneNumbers<WithStreamedUnaryMethod_ListPhone<WithStreamedUnaryMethod_FindPhoneById<WithStreamedUnaryMethod_UpdatePhone<WithStreamedUnaryMethod_DeletePhone<Service > > > > > > StreamedService;
};

}  // namespace v1
}  // namespace account


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_account_2fv1_2fphone_2eproto__INCLUDED
