// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: account/v1/phone.proto

#include "account/v1/phone.pb.h"
#include "account/v1/phone.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace account {
namespace v1 {

static const char* PhoneService_method_names[] = {
  "/account.v1.PhoneService/CreatePhone",
  "/account.v1.PhoneService/ListPhoneNumbers",
  "/account.v1.PhoneService/ListPhone",
  "/account.v1.PhoneService/FindPhoneById",
  "/account.v1.PhoneService/UpdatePhone",
  "/account.v1.PhoneService/DeletePhone",
};

std::unique_ptr< PhoneService::Stub> PhoneService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PhoneService::Stub> stub(new PhoneService::Stub(channel, options));
  return stub;
}

PhoneService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreatePhone_(PhoneService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListPhoneNumbers_(PhoneService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListPhone_(PhoneService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindPhoneById_(PhoneService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdatePhone_(PhoneService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeletePhone_(PhoneService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PhoneService::Stub::CreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::account::v1::CreatePhoneResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::CreatePhoneReq, ::account::v1::CreatePhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreatePhone_, context, request, response);
}

void PhoneService::Stub::async::CreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq* request, ::account::v1::CreatePhoneResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::CreatePhoneReq, ::account::v1::CreatePhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreatePhone_, context, request, response, std::move(f));
}

void PhoneService::Stub::async::CreatePhone(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq* request, ::account::v1::CreatePhoneResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreatePhone_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::CreatePhoneResp>* PhoneService::Stub::PrepareAsyncCreatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::CreatePhoneResp, ::account::v1::CreatePhoneReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreatePhone_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::CreatePhoneResp>* PhoneService::Stub::AsyncCreatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::CreatePhoneReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreatePhoneRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PhoneService::Stub::ListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::account::v1::ListPhoneNumbersResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::ListPhoneNumbersReq, ::account::v1::ListPhoneNumbersResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListPhoneNumbers_, context, request, response);
}

void PhoneService::Stub::async::ListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq* request, ::account::v1::ListPhoneNumbersResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::ListPhoneNumbersReq, ::account::v1::ListPhoneNumbersResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPhoneNumbers_, context, request, response, std::move(f));
}

void PhoneService::Stub::async::ListPhoneNumbers(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq* request, ::account::v1::ListPhoneNumbersResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPhoneNumbers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneNumbersResp>* PhoneService::Stub::PrepareAsyncListPhoneNumbersRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::ListPhoneNumbersResp, ::account::v1::ListPhoneNumbersReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListPhoneNumbers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneNumbersResp>* PhoneService::Stub::AsyncListPhoneNumbersRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneNumbersReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListPhoneNumbersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PhoneService::Stub::ListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::account::v1::ListPhoneResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::ListPhoneReq, ::account::v1::ListPhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListPhone_, context, request, response);
}

void PhoneService::Stub::async::ListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq* request, ::account::v1::ListPhoneResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::ListPhoneReq, ::account::v1::ListPhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPhone_, context, request, response, std::move(f));
}

void PhoneService::Stub::async::ListPhone(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq* request, ::account::v1::ListPhoneResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPhone_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneResp>* PhoneService::Stub::PrepareAsyncListPhoneRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::ListPhoneResp, ::account::v1::ListPhoneReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListPhone_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::ListPhoneResp>* PhoneService::Stub::AsyncListPhoneRaw(::grpc::ClientContext* context, const ::account::v1::ListPhoneReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListPhoneRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PhoneService::Stub::FindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::account::v1::FindPhoneByIdResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::FindPhoneByIdReq, ::account::v1::FindPhoneByIdResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FindPhoneById_, context, request, response);
}

void PhoneService::Stub::async::FindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq* request, ::account::v1::FindPhoneByIdResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::FindPhoneByIdReq, ::account::v1::FindPhoneByIdResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindPhoneById_, context, request, response, std::move(f));
}

void PhoneService::Stub::async::FindPhoneById(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq* request, ::account::v1::FindPhoneByIdResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindPhoneById_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::FindPhoneByIdResp>* PhoneService::Stub::PrepareAsyncFindPhoneByIdRaw(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::FindPhoneByIdResp, ::account::v1::FindPhoneByIdReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FindPhoneById_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::FindPhoneByIdResp>* PhoneService::Stub::AsyncFindPhoneByIdRaw(::grpc::ClientContext* context, const ::account::v1::FindPhoneByIdReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFindPhoneByIdRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PhoneService::Stub::UpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::account::v1::UpdatePhoneResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::UpdatePhoneReq, ::account::v1::UpdatePhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdatePhone_, context, request, response);
}

void PhoneService::Stub::async::UpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq* request, ::account::v1::UpdatePhoneResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::UpdatePhoneReq, ::account::v1::UpdatePhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdatePhone_, context, request, response, std::move(f));
}

void PhoneService::Stub::async::UpdatePhone(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq* request, ::account::v1::UpdatePhoneResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdatePhone_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::UpdatePhoneResp>* PhoneService::Stub::PrepareAsyncUpdatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::UpdatePhoneResp, ::account::v1::UpdatePhoneReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdatePhone_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::UpdatePhoneResp>* PhoneService::Stub::AsyncUpdatePhoneRaw(::grpc::ClientContext* context, const ::account::v1::UpdatePhoneReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdatePhoneRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PhoneService::Stub::DeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::account::v1::DeletePhoneResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::account::v1::DeletePhoneReq, ::account::v1::DeletePhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeletePhone_, context, request, response);
}

void PhoneService::Stub::async::DeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq* request, ::account::v1::DeletePhoneResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::account::v1::DeletePhoneReq, ::account::v1::DeletePhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeletePhone_, context, request, response, std::move(f));
}

void PhoneService::Stub::async::DeletePhone(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq* request, ::account::v1::DeletePhoneResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeletePhone_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::account::v1::DeletePhoneResp>* PhoneService::Stub::PrepareAsyncDeletePhoneRaw(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::account::v1::DeletePhoneResp, ::account::v1::DeletePhoneReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeletePhone_, context, request);
}

::grpc::ClientAsyncResponseReader< ::account::v1::DeletePhoneResp>* PhoneService::Stub::AsyncDeletePhoneRaw(::grpc::ClientContext* context, const ::account::v1::DeletePhoneReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeletePhoneRaw(context, request, cq);
  result->StartCall();
  return result;
}

PhoneService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PhoneService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PhoneService::Service, ::account::v1::CreatePhoneReq, ::account::v1::CreatePhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PhoneService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::CreatePhoneReq* req,
             ::account::v1::CreatePhoneResp* resp) {
               return service->CreatePhone(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PhoneService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PhoneService::Service, ::account::v1::ListPhoneNumbersReq, ::account::v1::ListPhoneNumbersResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PhoneService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::ListPhoneNumbersReq* req,
             ::account::v1::ListPhoneNumbersResp* resp) {
               return service->ListPhoneNumbers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PhoneService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PhoneService::Service, ::account::v1::ListPhoneReq, ::account::v1::ListPhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PhoneService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::ListPhoneReq* req,
             ::account::v1::ListPhoneResp* resp) {
               return service->ListPhone(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PhoneService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PhoneService::Service, ::account::v1::FindPhoneByIdReq, ::account::v1::FindPhoneByIdResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PhoneService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::FindPhoneByIdReq* req,
             ::account::v1::FindPhoneByIdResp* resp) {
               return service->FindPhoneById(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PhoneService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PhoneService::Service, ::account::v1::UpdatePhoneReq, ::account::v1::UpdatePhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PhoneService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::UpdatePhoneReq* req,
             ::account::v1::UpdatePhoneResp* resp) {
               return service->UpdatePhone(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PhoneService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PhoneService::Service, ::account::v1::DeletePhoneReq, ::account::v1::DeletePhoneResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PhoneService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::account::v1::DeletePhoneReq* req,
             ::account::v1::DeletePhoneResp* resp) {
               return service->DeletePhone(ctx, req, resp);
             }, this)));
}

PhoneService::Service::~Service() {
}

::grpc::Status PhoneService::Service::CreatePhone(::grpc::ServerContext* context, const ::account::v1::CreatePhoneReq* request, ::account::v1::CreatePhoneResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PhoneService::Service::ListPhoneNumbers(::grpc::ServerContext* context, const ::account::v1::ListPhoneNumbersReq* request, ::account::v1::ListPhoneNumbersResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PhoneService::Service::ListPhone(::grpc::ServerContext* context, const ::account::v1::ListPhoneReq* request, ::account::v1::ListPhoneResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PhoneService::Service::FindPhoneById(::grpc::ServerContext* context, const ::account::v1::FindPhoneByIdReq* request, ::account::v1::FindPhoneByIdResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PhoneService::Service::UpdatePhone(::grpc::ServerContext* context, const ::account::v1::UpdatePhoneReq* request, ::account::v1::UpdatePhoneResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PhoneService::Service::DeletePhone(::grpc::ServerContext* context, const ::account::v1::DeletePhoneReq* request, ::account::v1::DeletePhoneResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace account
}  // namespace v1

