// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account/v1/telecom.proto
// Protobuf C++ Version: 5.29.0

#ifndef account_2fv1_2ftelecom_2eproto_2epb_2eh
#define account_2fv1_2ftelecom_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_account_2fv1_2ftelecom_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_account_2fv1_2ftelecom_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_account_2fv1_2ftelecom_2eproto;
namespace account {
namespace v1 {
class ListTelecomOperatorReq;
struct ListTelecomOperatorReqDefaultTypeInternal;
extern ListTelecomOperatorReqDefaultTypeInternal _ListTelecomOperatorReq_default_instance_;
class ListTelecomOperatorResp;
struct ListTelecomOperatorRespDefaultTypeInternal;
extern ListTelecomOperatorRespDefaultTypeInternal _ListTelecomOperatorResp_default_instance_;
}  // namespace v1
}  // namespace account
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace account {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class ListTelecomOperatorResp final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:account.v1.ListTelecomOperatorResp) */ {
 public:
  inline ListTelecomOperatorResp() : ListTelecomOperatorResp(nullptr) {}
  ~ListTelecomOperatorResp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ListTelecomOperatorResp* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ListTelecomOperatorResp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListTelecomOperatorResp(
      ::google::protobuf::internal::ConstantInitialized);

  inline ListTelecomOperatorResp(const ListTelecomOperatorResp& from) : ListTelecomOperatorResp(nullptr, from) {}
  inline ListTelecomOperatorResp(ListTelecomOperatorResp&& from) noexcept
      : ListTelecomOperatorResp(nullptr, std::move(from)) {}
  inline ListTelecomOperatorResp& operator=(const ListTelecomOperatorResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListTelecomOperatorResp& operator=(ListTelecomOperatorResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListTelecomOperatorResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListTelecomOperatorResp* internal_default_instance() {
    return reinterpret_cast<const ListTelecomOperatorResp*>(
        &_ListTelecomOperatorResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ListTelecomOperatorResp& a, ListTelecomOperatorResp& b) { a.Swap(&b); }
  inline void Swap(ListTelecomOperatorResp* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListTelecomOperatorResp* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListTelecomOperatorResp* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ListTelecomOperatorResp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListTelecomOperatorResp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListTelecomOperatorResp& from) { ListTelecomOperatorResp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ListTelecomOperatorResp* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "account.v1.ListTelecomOperatorResp"; }

 protected:
  explicit ListTelecomOperatorResp(::google::protobuf::Arena* arena);
  ListTelecomOperatorResp(::google::protobuf::Arena* arena, const ListTelecomOperatorResp& from);
  ListTelecomOperatorResp(::google::protobuf::Arena* arena, ListTelecomOperatorResp&& from) noexcept
      : ListTelecomOperatorResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTelecomsFieldNumber = 1,
    kMessageFieldNumber = 2,
  };
  // repeated string telecoms = 1;
  int telecoms_size() const;
  private:
  int _internal_telecoms_size() const;

  public:
  void clear_telecoms() ;
  const std::string& telecoms(int index) const;
  std::string* mutable_telecoms(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_telecoms(int index, Arg_&& value, Args_... args);
  std::string* add_telecoms();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_telecoms(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& telecoms() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_telecoms();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_telecoms() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_telecoms();

  public:
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // @@protoc_insertion_point(class_scope:account.v1.ListTelecomOperatorResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      58, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ListTelecomOperatorResp& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> telecoms_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_account_2fv1_2ftelecom_2eproto;
};
// -------------------------------------------------------------------

class ListTelecomOperatorReq final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:account.v1.ListTelecomOperatorReq) */ {
 public:
  inline ListTelecomOperatorReq() : ListTelecomOperatorReq(nullptr) {}
  ~ListTelecomOperatorReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ListTelecomOperatorReq* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ListTelecomOperatorReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListTelecomOperatorReq(
      ::google::protobuf::internal::ConstantInitialized);

  inline ListTelecomOperatorReq(const ListTelecomOperatorReq& from) : ListTelecomOperatorReq(nullptr, from) {}
  inline ListTelecomOperatorReq(ListTelecomOperatorReq&& from) noexcept
      : ListTelecomOperatorReq(nullptr, std::move(from)) {}
  inline ListTelecomOperatorReq& operator=(const ListTelecomOperatorReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListTelecomOperatorReq& operator=(ListTelecomOperatorReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListTelecomOperatorReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListTelecomOperatorReq* internal_default_instance() {
    return reinterpret_cast<const ListTelecomOperatorReq*>(
        &_ListTelecomOperatorReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ListTelecomOperatorReq& a, ListTelecomOperatorReq& b) { a.Swap(&b); }
  inline void Swap(ListTelecomOperatorReq* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListTelecomOperatorReq* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListTelecomOperatorReq* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ListTelecomOperatorReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListTelecomOperatorReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListTelecomOperatorReq& from) { ListTelecomOperatorReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ListTelecomOperatorReq* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "account.v1.ListTelecomOperatorReq"; }

 protected:
  explicit ListTelecomOperatorReq(::google::protobuf::Arena* arena);
  ListTelecomOperatorReq(::google::protobuf::Arena* arena, const ListTelecomOperatorReq& from);
  ListTelecomOperatorReq(::google::protobuf::Arena* arena, ListTelecomOperatorReq&& from) noexcept
      : ListTelecomOperatorReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 1,
  };
  // string session_id = 1;
  void clear_session_id() ;
  const std::string& session_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_session_id(Arg_&& arg, Args_... args);
  std::string* mutable_session_id();
  PROTOBUF_NODISCARD std::string* release_session_id();
  void set_allocated_session_id(std::string* value);

  private:
  const std::string& _internal_session_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(
      const std::string& value);
  std::string* _internal_mutable_session_id();

  public:
  // @@protoc_insertion_point(class_scope:account.v1.ListTelecomOperatorReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      52, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ListTelecomOperatorReq& from_msg);
    ::google::protobuf::internal::ArenaStringPtr session_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_account_2fv1_2ftelecom_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ListTelecomOperatorReq

// string session_id = 1;
inline void ListTelecomOperatorReq::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.ClearToEmpty();
}
inline const std::string& ListTelecomOperatorReq::session_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:account.v1.ListTelecomOperatorReq.session_id)
  return _internal_session_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ListTelecomOperatorReq::set_session_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:account.v1.ListTelecomOperatorReq.session_id)
}
inline std::string* ListTelecomOperatorReq::mutable_session_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:account.v1.ListTelecomOperatorReq.session_id)
  return _s;
}
inline const std::string& ListTelecomOperatorReq::_internal_session_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_id_.Get();
}
inline void ListTelecomOperatorReq::_internal_set_session_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.Set(value, GetArena());
}
inline std::string* ListTelecomOperatorReq::_internal_mutable_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_id_.Mutable( GetArena());
}
inline std::string* ListTelecomOperatorReq::release_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:account.v1.ListTelecomOperatorReq.session_id)
  return _impl_.session_id_.Release();
}
inline void ListTelecomOperatorReq::set_allocated_session_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:account.v1.ListTelecomOperatorReq.session_id)
}

// -------------------------------------------------------------------

// ListTelecomOperatorResp

// repeated string telecoms = 1;
inline int ListTelecomOperatorResp::_internal_telecoms_size() const {
  return _internal_telecoms().size();
}
inline int ListTelecomOperatorResp::telecoms_size() const {
  return _internal_telecoms_size();
}
inline void ListTelecomOperatorResp::clear_telecoms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.telecoms_.Clear();
}
inline std::string* ListTelecomOperatorResp::add_telecoms() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_telecoms()->Add();
  // @@protoc_insertion_point(field_add_mutable:account.v1.ListTelecomOperatorResp.telecoms)
  return _s;
}
inline const std::string& ListTelecomOperatorResp::telecoms(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:account.v1.ListTelecomOperatorResp.telecoms)
  return _internal_telecoms().Get(index);
}
inline std::string* ListTelecomOperatorResp::mutable_telecoms(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:account.v1.ListTelecomOperatorResp.telecoms)
  return _internal_mutable_telecoms()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ListTelecomOperatorResp::set_telecoms(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_telecoms()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:account.v1.ListTelecomOperatorResp.telecoms)
}
template <typename Arg_, typename... Args_>
inline void ListTelecomOperatorResp::add_telecoms(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_telecoms(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:account.v1.ListTelecomOperatorResp.telecoms)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ListTelecomOperatorResp::telecoms() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:account.v1.ListTelecomOperatorResp.telecoms)
  return _internal_telecoms();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ListTelecomOperatorResp::mutable_telecoms() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:account.v1.ListTelecomOperatorResp.telecoms)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_telecoms();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ListTelecomOperatorResp::_internal_telecoms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.telecoms_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ListTelecomOperatorResp::_internal_mutable_telecoms() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.telecoms_;
}

// string message = 2;
inline void ListTelecomOperatorResp::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ListTelecomOperatorResp::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:account.v1.ListTelecomOperatorResp.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ListTelecomOperatorResp::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:account.v1.ListTelecomOperatorResp.message)
}
inline std::string* ListTelecomOperatorResp::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:account.v1.ListTelecomOperatorResp.message)
  return _s;
}
inline const std::string& ListTelecomOperatorResp::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void ListTelecomOperatorResp::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* ListTelecomOperatorResp::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* ListTelecomOperatorResp::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:account.v1.ListTelecomOperatorResp.message)
  return _impl_.message_.Release();
}
inline void ListTelecomOperatorResp::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:account.v1.ListTelecomOperatorResp.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace account


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // account_2fv1_2ftelecom_2eproto_2epb_2eh
