// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: account/v1/telecom.proto
#ifndef GRPC_account_2fv1_2ftelecom_2eproto__INCLUDED
#define GRPC_account_2fv1_2ftelecom_2eproto__INCLUDED

#include "account/v1/telecom.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace account {
namespace v1 {

class TelecomService final {
 public:
  static constexpr char const* service_full_name() {
    return "account.v1.TelecomService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::account::v1::ListTelecomOperatorResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListTelecomOperatorResp>> AsyncListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListTelecomOperatorResp>>(AsyncListTelecomOperatorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListTelecomOperatorResp>> PrepareAsyncListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListTelecomOperatorResp>>(PrepareAsyncListTelecomOperatorRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq* request, ::account::v1::ListTelecomOperatorResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq* request, ::account::v1::ListTelecomOperatorResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListTelecomOperatorResp>* AsyncListTelecomOperatorRaw(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::v1::ListTelecomOperatorResp>* PrepareAsyncListTelecomOperatorRaw(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::account::v1::ListTelecomOperatorResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListTelecomOperatorResp>> AsyncListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListTelecomOperatorResp>>(AsyncListTelecomOperatorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListTelecomOperatorResp>> PrepareAsyncListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::v1::ListTelecomOperatorResp>>(PrepareAsyncListTelecomOperatorRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq* request, ::account::v1::ListTelecomOperatorResp* response, std::function<void(::grpc::Status)>) override;
      void ListTelecomOperator(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq* request, ::account::v1::ListTelecomOperatorResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::account::v1::ListTelecomOperatorResp>* AsyncListTelecomOperatorRaw(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::v1::ListTelecomOperatorResp>* PrepareAsyncListTelecomOperatorRaw(::grpc::ClientContext* context, const ::account::v1::ListTelecomOperatorReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListTelecomOperator_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ListTelecomOperator(::grpc::ServerContext* context, const ::account::v1::ListTelecomOperatorReq* request, ::account::v1::ListTelecomOperatorResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListTelecomOperator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListTelecomOperator() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListTelecomOperator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListTelecomOperator(::grpc::ServerContext* /*context*/, const ::account::v1::ListTelecomOperatorReq* /*request*/, ::account::v1::ListTelecomOperatorResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListTelecomOperator(::grpc::ServerContext* context, ::account::v1::ListTelecomOperatorReq* request, ::grpc::ServerAsyncResponseWriter< ::account::v1::ListTelecomOperatorResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListTelecomOperator<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ListTelecomOperator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListTelecomOperator() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::account::v1::ListTelecomOperatorReq, ::account::v1::ListTelecomOperatorResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::v1::ListTelecomOperatorReq* request, ::account::v1::ListTelecomOperatorResp* response) { return this->ListTelecomOperator(context, request, response); }));}
    void SetMessageAllocatorFor_ListTelecomOperator(
        ::grpc::MessageAllocator< ::account::v1::ListTelecomOperatorReq, ::account::v1::ListTelecomOperatorResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::v1::ListTelecomOperatorReq, ::account::v1::ListTelecomOperatorResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListTelecomOperator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListTelecomOperator(::grpc::ServerContext* /*context*/, const ::account::v1::ListTelecomOperatorReq* /*request*/, ::account::v1::ListTelecomOperatorResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListTelecomOperator(
      ::grpc::CallbackServerContext* /*context*/, const ::account::v1::ListTelecomOperatorReq* /*request*/, ::account::v1::ListTelecomOperatorResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ListTelecomOperator<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListTelecomOperator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListTelecomOperator() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListTelecomOperator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListTelecomOperator(::grpc::ServerContext* /*context*/, const ::account::v1::ListTelecomOperatorReq* /*request*/, ::account::v1::ListTelecomOperatorResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListTelecomOperator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListTelecomOperator() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListTelecomOperator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListTelecomOperator(::grpc::ServerContext* /*context*/, const ::account::v1::ListTelecomOperatorReq* /*request*/, ::account::v1::ListTelecomOperatorResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListTelecomOperator(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListTelecomOperator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListTelecomOperator() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListTelecomOperator(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListTelecomOperator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListTelecomOperator(::grpc::ServerContext* /*context*/, const ::account::v1::ListTelecomOperatorReq* /*request*/, ::account::v1::ListTelecomOperatorResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListTelecomOperator(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListTelecomOperator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListTelecomOperator() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::v1::ListTelecomOperatorReq, ::account::v1::ListTelecomOperatorResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::v1::ListTelecomOperatorReq, ::account::v1::ListTelecomOperatorResp>* streamer) {
                       return this->StreamedListTelecomOperator(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListTelecomOperator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListTelecomOperator(::grpc::ServerContext* /*context*/, const ::account::v1::ListTelecomOperatorReq* /*request*/, ::account::v1::ListTelecomOperatorResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListTelecomOperator(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::v1::ListTelecomOperatorReq,::account::v1::ListTelecomOperatorResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListTelecomOperator<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListTelecomOperator<Service > StreamedService;
};

}  // namespace v1
}  // namespace account


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_account_2fv1_2ftelecom_2eproto__INCLUDED
