// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user/v1/auth.proto
#ifndef GRPC_user_2fv1_2fauth_2eproto__INCLUDED
#define GRPC_user_2fv1_2fauth_2eproto__INCLUDED

#include "user/v1/auth.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace user {
namespace v1 {

// import "common/v1/common.proto";
//
class AuthService final {
 public:
  static constexpr char const* service_full_name() {
    return "user.v1.AuthService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::user::v1::AuthUserResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::AuthUserResp>> AsyncAuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::AuthUserResp>>(AsyncAuthUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::AuthUserResp>> PrepareAsyncAuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::AuthUserResp>>(PrepareAsyncAuthUserRaw(context, request, cq));
    }
    // 验证身份
    virtual ::grpc::Status CreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::user::v1::CreateSessionResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateSessionResp>> AsyncCreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateSessionResp>>(AsyncCreateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateSessionResp>> PrepareAsyncCreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateSessionResp>>(PrepareAsyncCreateSessionRaw(context, request, cq));
    }
    // 创建会话（登录）
    virtual ::grpc::Status UpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::user::v1::UpdateSessionResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateSessionResp>> AsyncUpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateSessionResp>>(AsyncUpdateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateSessionResp>> PrepareAsyncUpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateSessionResp>>(PrepareAsyncUpdateSessionRaw(context, request, cq));
    }
    // 更新会话
    virtual ::grpc::Status DeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::user::v1::DeleteSessionResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::DeleteSessionResp>> AsyncDeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::DeleteSessionResp>>(AsyncDeleteSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::DeleteSessionResp>> PrepareAsyncDeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::DeleteSessionResp>>(PrepareAsyncDeleteSessionRaw(context, request, cq));
    }
    // 删除会话（登出）
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq* request, ::user::v1::AuthUserResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq* request, ::user::v1::AuthUserResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 验证身份
      virtual void CreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq* request, ::user::v1::CreateSessionResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq* request, ::user::v1::CreateSessionResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 创建会话（登录）
      virtual void UpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq* request, ::user::v1::UpdateSessionResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq* request, ::user::v1::UpdateSessionResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 更新会话
      virtual void DeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq* request, ::user::v1::DeleteSessionResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq* request, ::user::v1::DeleteSessionResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 删除会话（登出）
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::AuthUserResp>* AsyncAuthUserRaw(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::AuthUserResp>* PrepareAsyncAuthUserRaw(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateSessionResp>* AsyncCreateSessionRaw(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateSessionResp>* PrepareAsyncCreateSessionRaw(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateSessionResp>* AsyncUpdateSessionRaw(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateSessionResp>* PrepareAsyncUpdateSessionRaw(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::DeleteSessionResp>* AsyncDeleteSessionRaw(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::DeleteSessionResp>* PrepareAsyncDeleteSessionRaw(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::user::v1::AuthUserResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::AuthUserResp>> AsyncAuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::AuthUserResp>>(AsyncAuthUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::AuthUserResp>> PrepareAsyncAuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::AuthUserResp>>(PrepareAsyncAuthUserRaw(context, request, cq));
    }
    ::grpc::Status CreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::user::v1::CreateSessionResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::CreateSessionResp>> AsyncCreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::CreateSessionResp>>(AsyncCreateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::CreateSessionResp>> PrepareAsyncCreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::CreateSessionResp>>(PrepareAsyncCreateSessionRaw(context, request, cq));
    }
    ::grpc::Status UpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::user::v1::UpdateSessionResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateSessionResp>> AsyncUpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateSessionResp>>(AsyncUpdateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateSessionResp>> PrepareAsyncUpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateSessionResp>>(PrepareAsyncUpdateSessionRaw(context, request, cq));
    }
    ::grpc::Status DeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::user::v1::DeleteSessionResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::DeleteSessionResp>> AsyncDeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::DeleteSessionResp>>(AsyncDeleteSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::DeleteSessionResp>> PrepareAsyncDeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::DeleteSessionResp>>(PrepareAsyncDeleteSessionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq* request, ::user::v1::AuthUserResp* response, std::function<void(::grpc::Status)>) override;
      void AuthUser(::grpc::ClientContext* context, const ::user::v1::AuthUserReq* request, ::user::v1::AuthUserResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq* request, ::user::v1::CreateSessionResp* response, std::function<void(::grpc::Status)>) override;
      void CreateSession(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq* request, ::user::v1::CreateSessionResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq* request, ::user::v1::UpdateSessionResp* response, std::function<void(::grpc::Status)>) override;
      void UpdateSession(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq* request, ::user::v1::UpdateSessionResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq* request, ::user::v1::DeleteSessionResp* response, std::function<void(::grpc::Status)>) override;
      void DeleteSession(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq* request, ::user::v1::DeleteSessionResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::user::v1::AuthUserResp>* AsyncAuthUserRaw(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::AuthUserResp>* PrepareAsyncAuthUserRaw(::grpc::ClientContext* context, const ::user::v1::AuthUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::CreateSessionResp>* AsyncCreateSessionRaw(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::CreateSessionResp>* PrepareAsyncCreateSessionRaw(::grpc::ClientContext* context, const ::user::v1::CreateSessionReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateSessionResp>* AsyncUpdateSessionRaw(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateSessionResp>* PrepareAsyncUpdateSessionRaw(::grpc::ClientContext* context, const ::user::v1::UpdateSessionReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::DeleteSessionResp>* AsyncDeleteSessionRaw(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::DeleteSessionResp>* PrepareAsyncDeleteSessionRaw(::grpc::ClientContext* context, const ::user::v1::DeleteSessionReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AuthUser_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateSession_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateSession_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteSession_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AuthUser(::grpc::ServerContext* context, const ::user::v1::AuthUserReq* request, ::user::v1::AuthUserResp* response);
    // 验证身份
    virtual ::grpc::Status CreateSession(::grpc::ServerContext* context, const ::user::v1::CreateSessionReq* request, ::user::v1::CreateSessionResp* response);
    // 创建会话（登录）
    virtual ::grpc::Status UpdateSession(::grpc::ServerContext* context, const ::user::v1::UpdateSessionReq* request, ::user::v1::UpdateSessionResp* response);
    // 更新会话
    virtual ::grpc::Status DeleteSession(::grpc::ServerContext* context, const ::user::v1::DeleteSessionReq* request, ::user::v1::DeleteSessionResp* response);
    // 删除会话（登出）
  };
  template <class BaseClass>
  class WithAsyncMethod_AuthUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AuthUser() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AuthUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthUser(::grpc::ServerContext* /*context*/, const ::user::v1::AuthUserReq* /*request*/, ::user::v1::AuthUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthUser(::grpc::ServerContext* context, ::user::v1::AuthUserReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::AuthUserResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateSession() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::user::v1::CreateSessionReq* /*request*/, ::user::v1::CreateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateSession(::grpc::ServerContext* context, ::user::v1::CreateSessionReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::CreateSessionResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateSession() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_UpdateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSession(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateSessionReq* /*request*/, ::user::v1::UpdateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateSession(::grpc::ServerContext* context, ::user::v1::UpdateSessionReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::UpdateSessionResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteSession() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_DeleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteSession(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteSessionReq* /*request*/, ::user::v1::DeleteSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteSession(::grpc::ServerContext* context, ::user::v1::DeleteSessionReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::DeleteSessionResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AuthUser<WithAsyncMethod_CreateSession<WithAsyncMethod_UpdateSession<WithAsyncMethod_DeleteSession<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AuthUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AuthUser() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::AuthUserReq, ::user::v1::AuthUserResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::AuthUserReq* request, ::user::v1::AuthUserResp* response) { return this->AuthUser(context, request, response); }));}
    void SetMessageAllocatorFor_AuthUser(
        ::grpc::MessageAllocator< ::user::v1::AuthUserReq, ::user::v1::AuthUserResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::AuthUserReq, ::user::v1::AuthUserResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AuthUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthUser(::grpc::ServerContext* /*context*/, const ::user::v1::AuthUserReq* /*request*/, ::user::v1::AuthUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthUser(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::AuthUserReq* /*request*/, ::user::v1::AuthUserResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateSession() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::CreateSessionReq, ::user::v1::CreateSessionResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::CreateSessionReq* request, ::user::v1::CreateSessionResp* response) { return this->CreateSession(context, request, response); }));}
    void SetMessageAllocatorFor_CreateSession(
        ::grpc::MessageAllocator< ::user::v1::CreateSessionReq, ::user::v1::CreateSessionResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::CreateSessionReq, ::user::v1::CreateSessionResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::user::v1::CreateSessionReq* /*request*/, ::user::v1::CreateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::CreateSessionReq* /*request*/, ::user::v1::CreateSessionResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateSession() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::UpdateSessionReq, ::user::v1::UpdateSessionResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::UpdateSessionReq* request, ::user::v1::UpdateSessionResp* response) { return this->UpdateSession(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateSession(
        ::grpc::MessageAllocator< ::user::v1::UpdateSessionReq, ::user::v1::UpdateSessionResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::UpdateSessionReq, ::user::v1::UpdateSessionResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSession(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateSessionReq* /*request*/, ::user::v1::UpdateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::UpdateSessionReq* /*request*/, ::user::v1::UpdateSessionResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteSession() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::DeleteSessionReq, ::user::v1::DeleteSessionResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::DeleteSessionReq* request, ::user::v1::DeleteSessionResp* response) { return this->DeleteSession(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteSession(
        ::grpc::MessageAllocator< ::user::v1::DeleteSessionReq, ::user::v1::DeleteSessionResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::DeleteSessionReq, ::user::v1::DeleteSessionResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteSession(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteSessionReq* /*request*/, ::user::v1::DeleteSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteSession(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::DeleteSessionReq* /*request*/, ::user::v1::DeleteSessionResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AuthUser<WithCallbackMethod_CreateSession<WithCallbackMethod_UpdateSession<WithCallbackMethod_DeleteSession<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AuthUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AuthUser() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AuthUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthUser(::grpc::ServerContext* /*context*/, const ::user::v1::AuthUserReq* /*request*/, ::user::v1::AuthUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateSession() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::user::v1::CreateSessionReq* /*request*/, ::user::v1::CreateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateSession() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_UpdateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSession(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateSessionReq* /*request*/, ::user::v1::UpdateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteSession() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_DeleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteSession(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteSessionReq* /*request*/, ::user::v1::DeleteSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AuthUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AuthUser() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AuthUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthUser(::grpc::ServerContext* /*context*/, const ::user::v1::AuthUserReq* /*request*/, ::user::v1::AuthUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateSession() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::user::v1::CreateSessionReq* /*request*/, ::user::v1::CreateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateSession() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_UpdateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSession(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateSessionReq* /*request*/, ::user::v1::UpdateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteSession() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_DeleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteSession(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteSessionReq* /*request*/, ::user::v1::DeleteSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AuthUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AuthUser() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AuthUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_AuthUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthUser(::grpc::ServerContext* /*context*/, const ::user::v1::AuthUserReq* /*request*/, ::user::v1::AuthUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateSession() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::user::v1::CreateSessionReq* /*request*/, ::user::v1::CreateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateSession() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSession(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateSessionReq* /*request*/, ::user::v1::UpdateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteSession() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteSession(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteSessionReq* /*request*/, ::user::v1::DeleteSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AuthUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AuthUser() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::AuthUserReq, ::user::v1::AuthUserResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::AuthUserReq, ::user::v1::AuthUserResp>* streamer) {
                       return this->StreamedAuthUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AuthUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AuthUser(::grpc::ServerContext* /*context*/, const ::user::v1::AuthUserReq* /*request*/, ::user::v1::AuthUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAuthUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::AuthUserReq,::user::v1::AuthUserResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateSession() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::CreateSessionReq, ::user::v1::CreateSessionResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::CreateSessionReq, ::user::v1::CreateSessionResp>* streamer) {
                       return this->StreamedCreateSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::user::v1::CreateSessionReq* /*request*/, ::user::v1::CreateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::CreateSessionReq,::user::v1::CreateSessionResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateSession() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::UpdateSessionReq, ::user::v1::UpdateSessionResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::UpdateSessionReq, ::user::v1::UpdateSessionResp>* streamer) {
                       return this->StreamedUpdateSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateSession(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateSessionReq* /*request*/, ::user::v1::UpdateSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::UpdateSessionReq,::user::v1::UpdateSessionResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteSession() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::DeleteSessionReq, ::user::v1::DeleteSessionResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::DeleteSessionReq, ::user::v1::DeleteSessionResp>* streamer) {
                       return this->StreamedDeleteSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteSession(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteSessionReq* /*request*/, ::user::v1::DeleteSessionResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::DeleteSessionReq,::user::v1::DeleteSessionResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AuthUser<WithStreamedUnaryMethod_CreateSession<WithStreamedUnaryMethod_UpdateSession<WithStreamedUnaryMethod_DeleteSession<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AuthUser<WithStreamedUnaryMethod_CreateSession<WithStreamedUnaryMethod_UpdateSession<WithStreamedUnaryMethod_DeleteSession<Service > > > > StreamedService;
};

}  // namespace v1
}  // namespace user


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_user_2fv1_2fauth_2eproto__INCLUDED
