// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user/v1/auth.proto
// Protobuf C++ Version: 5.29.0

#include "user/v1/auth.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace user {
namespace v1 {
              template <typename>
PROTOBUF_CONSTEXPR UpdateSessionResp::UpdateSessionResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct UpdateSessionRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateSessionRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateSessionRespDefaultTypeInternal() {}
  union {
    UpdateSessionResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateSessionRespDefaultTypeInternal _UpdateSessionResp_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR UpdateSessionReq::UpdateSessionReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct UpdateSessionReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateSessionReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateSessionReqDefaultTypeInternal() {}
  union {
    UpdateSessionReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateSessionReqDefaultTypeInternal _UpdateSessionReq_default_instance_;

inline constexpr DeleteSessionResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DeleteSessionResp::DeleteSessionResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DeleteSessionRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeleteSessionRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeleteSessionRespDefaultTypeInternal() {}
  union {
    DeleteSessionResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeleteSessionRespDefaultTypeInternal _DeleteSessionResp_default_instance_;

inline constexpr DeleteSessionReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : session_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DeleteSessionReq::DeleteSessionReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DeleteSessionReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeleteSessionReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeleteSessionReqDefaultTypeInternal() {}
  union {
    DeleteSessionReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeleteSessionReqDefaultTypeInternal _DeleteSessionReq_default_instance_;

inline constexpr CreateSessionResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : session_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CreateSessionResp::CreateSessionResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CreateSessionRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateSessionRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateSessionRespDefaultTypeInternal() {}
  union {
    CreateSessionResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateSessionRespDefaultTypeInternal _CreateSessionResp_default_instance_;

inline constexpr CreateSessionReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        main_key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        captcha_input_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CreateSessionReq::CreateSessionReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CreateSessionReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateSessionReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateSessionReqDefaultTypeInternal() {}
  union {
    CreateSessionReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateSessionReqDefaultTypeInternal _CreateSessionReq_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR AuthUserResp::AuthUserResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct AuthUserRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthUserRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthUserRespDefaultTypeInternal() {}
  union {
    AuthUserResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthUserRespDefaultTypeInternal _AuthUserResp_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR AuthUserReq::AuthUserReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct AuthUserReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthUserReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthUserReqDefaultTypeInternal() {}
  union {
    AuthUserReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthUserReqDefaultTypeInternal _AuthUserReq_default_instance_;
}  // namespace v1
}  // namespace user
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_user_2fv1_2fauth_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_user_2fv1_2fauth_2eproto = nullptr;
const ::uint32_t
    TableStruct_user_2fv1_2fauth_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::v1::AuthUserReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::v1::AuthUserResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionReq, _impl_.username_),
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionReq, _impl_.main_key_),
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionReq, _impl_.captcha_input_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionResp, _impl_.session_id_),
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionResp, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionResp, _impl_.username_),
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionResp, _impl_.nickname_),
        PROTOBUF_FIELD_OFFSET(::user::v1::CreateSessionResp, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::v1::UpdateSessionReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::v1::UpdateSessionResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::v1::DeleteSessionReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::v1::DeleteSessionReq, _impl_.session_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::v1::DeleteSessionResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::v1::DeleteSessionResp, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::user::v1::AuthUserReq)},
        {8, -1, -1, sizeof(::user::v1::AuthUserResp)},
        {16, -1, -1, sizeof(::user::v1::CreateSessionReq)},
        {27, -1, -1, sizeof(::user::v1::CreateSessionResp)},
        {40, -1, -1, sizeof(::user::v1::UpdateSessionReq)},
        {48, -1, -1, sizeof(::user::v1::UpdateSessionResp)},
        {56, -1, -1, sizeof(::user::v1::DeleteSessionReq)},
        {65, -1, -1, sizeof(::user::v1::DeleteSessionResp)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::user::v1::_AuthUserReq_default_instance_._instance,
    &::user::v1::_AuthUserResp_default_instance_._instance,
    &::user::v1::_CreateSessionReq_default_instance_._instance,
    &::user::v1::_CreateSessionResp_default_instance_._instance,
    &::user::v1::_UpdateSessionReq_default_instance_._instance,
    &::user::v1::_UpdateSessionResp_default_instance_._instance,
    &::user::v1::_DeleteSessionReq_default_instance_._instance,
    &::user::v1::_DeleteSessionResp_default_instance_._instance,
};
const char descriptor_table_protodef_user_2fv1_2fauth_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022user/v1/auth.proto\022\007user.v1\"\r\n\013AuthUse"
    "rReq\"\016\n\014AuthUserResp\"M\n\020CreateSessionReq"
    "\022\020\n\010username\030\001 \001(\t\022\020\n\010main_key\030\002 \001(\t\022\025\n\r"
    "captcha_input\030\003 \001(\t\"m\n\021CreateSessionResp"
    "\022\022\n\nsession_id\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\t\022\020\n"
    "\010username\030\003 \001(\t\022\020\n\010nickname\030\004 \001(\t\022\017\n\007mes"
    "sage\030\020 \001(\t\"\022\n\020UpdateSessionReq\"\023\n\021Update"
    "SessionResp\"&\n\020DeleteSessionReq\022\022\n\nsessi"
    "on_id\030\001 \001(\t\"$\n\021DeleteSessionResp\022\017\n\007mess"
    "age\030\001 \001(\t2\236\002\n\013AuthService\0227\n\010AuthUser\022\024."
    "user.v1.AuthUserReq\032\025.user.v1.AuthUserRe"
    "sp\022F\n\rCreateSession\022\031.user.v1.CreateSess"
    "ionReq\032\032.user.v1.CreateSessionResp\022F\n\rUp"
    "dateSession\022\031.user.v1.UpdateSessionReq\032\032"
    ".user.v1.UpdateSessionResp\022F\n\rDeleteSess"
    "ion\022\031.user.v1.DeleteSessionReq\032\032.user.v1"
    ".DeleteSessionRespb\006proto3"
};
static ::absl::once_flag descriptor_table_user_2fv1_2fauth_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_user_2fv1_2fauth_2eproto = {
    false,
    false,
    666,
    descriptor_table_protodef_user_2fv1_2fauth_2eproto,
    "user/v1/auth.proto",
    &descriptor_table_user_2fv1_2fauth_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_user_2fv1_2fauth_2eproto::offsets,
    file_level_enum_descriptors_user_2fv1_2fauth_2eproto,
    file_level_service_descriptors_user_2fv1_2fauth_2eproto,
};
namespace user {
namespace v1 {
// ===================================================================

class AuthUserReq::_Internal {
 public:
};

AuthUserReq::AuthUserReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:user.v1.AuthUserReq)
}
AuthUserReq::AuthUserReq(
    ::google::protobuf::Arena* arena,
    const AuthUserReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AuthUserReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:user.v1.AuthUserReq)
}

inline void* AuthUserReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AuthUserReq(arena);
}
constexpr auto AuthUserReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AuthUserReq),
                                            alignof(AuthUserReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AuthUserReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AuthUserReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AuthUserReq::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<AuthUserReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AuthUserReq::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<AuthUserReq>(), &AuthUserReq::ByteSizeLong,
            &AuthUserReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AuthUserReq, _impl_._cached_size_),
        false,
    },
    &AuthUserReq::kDescriptorMethods,
    &descriptor_table_user_2fv1_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AuthUserReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> AuthUserReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::v1::AuthUserReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata AuthUserReq::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AuthUserResp::_Internal {
 public:
};

AuthUserResp::AuthUserResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:user.v1.AuthUserResp)
}
AuthUserResp::AuthUserResp(
    ::google::protobuf::Arena* arena,
    const AuthUserResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AuthUserResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:user.v1.AuthUserResp)
}

inline void* AuthUserResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AuthUserResp(arena);
}
constexpr auto AuthUserResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AuthUserResp),
                                            alignof(AuthUserResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AuthUserResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AuthUserResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AuthUserResp::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<AuthUserResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AuthUserResp::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<AuthUserResp>(), &AuthUserResp::ByteSizeLong,
            &AuthUserResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AuthUserResp, _impl_._cached_size_),
        false,
    },
    &AuthUserResp::kDescriptorMethods,
    &descriptor_table_user_2fv1_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AuthUserResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> AuthUserResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::v1::AuthUserResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata AuthUserResp::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CreateSessionReq::_Internal {
 public:
};

CreateSessionReq::CreateSessionReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.v1.CreateSessionReq)
}
inline PROTOBUF_NDEBUG_INLINE CreateSessionReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::v1::CreateSessionReq& from_msg)
      : username_(arena, from.username_),
        main_key_(arena, from.main_key_),
        captcha_input_(arena, from.captcha_input_),
        _cached_size_{0} {}

CreateSessionReq::CreateSessionReq(
    ::google::protobuf::Arena* arena,
    const CreateSessionReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CreateSessionReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:user.v1.CreateSessionReq)
}
inline PROTOBUF_NDEBUG_INLINE CreateSessionReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : username_(arena),
        main_key_(arena),
        captcha_input_(arena),
        _cached_size_{0} {}

inline void CreateSessionReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CreateSessionReq::~CreateSessionReq() {
  // @@protoc_insertion_point(destructor:user.v1.CreateSessionReq)
  SharedDtor(*this);
}
inline void CreateSessionReq::SharedDtor(MessageLite& self) {
  CreateSessionReq& this_ = static_cast<CreateSessionReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.username_.Destroy();
  this_._impl_.main_key_.Destroy();
  this_._impl_.captcha_input_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CreateSessionReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CreateSessionReq(arena);
}
constexpr auto CreateSessionReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CreateSessionReq),
                                            alignof(CreateSessionReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CreateSessionReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CreateSessionReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CreateSessionReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CreateSessionReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CreateSessionReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CreateSessionReq>(), &CreateSessionReq::ByteSizeLong,
            &CreateSessionReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CreateSessionReq, _impl_._cached_size_),
        false,
    },
    &CreateSessionReq::kDescriptorMethods,
    &descriptor_table_user_2fv1_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CreateSessionReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 62, 2> CreateSessionReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::v1::CreateSessionReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string username = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CreateSessionReq, _impl_.username_)}},
    // string main_key = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CreateSessionReq, _impl_.main_key_)}},
    // string captcha_input = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(CreateSessionReq, _impl_.captcha_input_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string username = 1;
    {PROTOBUF_FIELD_OFFSET(CreateSessionReq, _impl_.username_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string main_key = 2;
    {PROTOBUF_FIELD_OFFSET(CreateSessionReq, _impl_.main_key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string captcha_input = 3;
    {PROTOBUF_FIELD_OFFSET(CreateSessionReq, _impl_.captcha_input_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\10\10\15\0\0\0\0"
    "user.v1.CreateSessionReq"
    "username"
    "main_key"
    "captcha_input"
  }},
};

PROTOBUF_NOINLINE void CreateSessionReq::Clear() {
// @@protoc_insertion_point(message_clear_start:user.v1.CreateSessionReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.username_.ClearToEmpty();
  _impl_.main_key_.ClearToEmpty();
  _impl_.captcha_input_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CreateSessionReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CreateSessionReq& this_ = static_cast<const CreateSessionReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CreateSessionReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CreateSessionReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.v1.CreateSessionReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string username = 1;
          if (!this_._internal_username().empty()) {
            const std::string& _s = this_._internal_username();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.CreateSessionReq.username");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string main_key = 2;
          if (!this_._internal_main_key().empty()) {
            const std::string& _s = this_._internal_main_key();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.CreateSessionReq.main_key");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string captcha_input = 3;
          if (!this_._internal_captcha_input().empty()) {
            const std::string& _s = this_._internal_captcha_input();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.CreateSessionReq.captcha_input");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.v1.CreateSessionReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CreateSessionReq::ByteSizeLong(const MessageLite& base) {
          const CreateSessionReq& this_ = static_cast<const CreateSessionReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CreateSessionReq::ByteSizeLong() const {
          const CreateSessionReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.v1.CreateSessionReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string username = 1;
            if (!this_._internal_username().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_username());
            }
            // string main_key = 2;
            if (!this_._internal_main_key().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_main_key());
            }
            // string captcha_input = 3;
            if (!this_._internal_captcha_input().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_captcha_input());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CreateSessionReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CreateSessionReq*>(&to_msg);
  auto& from = static_cast<const CreateSessionReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.v1.CreateSessionReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_username().empty()) {
    _this->_internal_set_username(from._internal_username());
  }
  if (!from._internal_main_key().empty()) {
    _this->_internal_set_main_key(from._internal_main_key());
  }
  if (!from._internal_captcha_input().empty()) {
    _this->_internal_set_captcha_input(from._internal_captcha_input());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CreateSessionReq::CopyFrom(const CreateSessionReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.v1.CreateSessionReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CreateSessionReq::InternalSwap(CreateSessionReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.main_key_, &other->_impl_.main_key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.captcha_input_, &other->_impl_.captcha_input_, arena);
}

::google::protobuf::Metadata CreateSessionReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CreateSessionResp::_Internal {
 public:
};

CreateSessionResp::CreateSessionResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.v1.CreateSessionResp)
}
inline PROTOBUF_NDEBUG_INLINE CreateSessionResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::v1::CreateSessionResp& from_msg)
      : session_id_(arena, from.session_id_),
        user_id_(arena, from.user_id_),
        username_(arena, from.username_),
        nickname_(arena, from.nickname_),
        message_(arena, from.message_),
        _cached_size_{0} {}

CreateSessionResp::CreateSessionResp(
    ::google::protobuf::Arena* arena,
    const CreateSessionResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CreateSessionResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:user.v1.CreateSessionResp)
}
inline PROTOBUF_NDEBUG_INLINE CreateSessionResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : session_id_(arena),
        user_id_(arena),
        username_(arena),
        nickname_(arena),
        message_(arena),
        _cached_size_{0} {}

inline void CreateSessionResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CreateSessionResp::~CreateSessionResp() {
  // @@protoc_insertion_point(destructor:user.v1.CreateSessionResp)
  SharedDtor(*this);
}
inline void CreateSessionResp::SharedDtor(MessageLite& self) {
  CreateSessionResp& this_ = static_cast<CreateSessionResp&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.session_id_.Destroy();
  this_._impl_.user_id_.Destroy();
  this_._impl_.username_.Destroy();
  this_._impl_.nickname_.Destroy();
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CreateSessionResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CreateSessionResp(arena);
}
constexpr auto CreateSessionResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CreateSessionResp),
                                            alignof(CreateSessionResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CreateSessionResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CreateSessionResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CreateSessionResp::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CreateSessionResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CreateSessionResp::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CreateSessionResp>(), &CreateSessionResp::ByteSizeLong,
            &CreateSessionResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_._cached_size_),
        false,
    },
    &CreateSessionResp::kDescriptorMethods,
    &descriptor_table_user_2fv1_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CreateSessionResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 74, 2> CreateSessionResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    16, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294934512,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::v1::CreateSessionResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 16;
    {::_pbi::TcParser::FastUS2,
     {386, 63, 0, PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.message_)}},
    // string session_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.session_id_)}},
    // string user_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.user_id_)}},
    // string username = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.username_)}},
    // string nickname = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.nickname_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string session_id = 1;
    {PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.session_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string user_id = 2;
    {PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string username = 3;
    {PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.username_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string nickname = 4;
    {PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.nickname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string message = 16;
    {PROTOBUF_FIELD_OFFSET(CreateSessionResp, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\12\7\10\10\7\0\0"
    "user.v1.CreateSessionResp"
    "session_id"
    "user_id"
    "username"
    "nickname"
    "message"
  }},
};

PROTOBUF_NOINLINE void CreateSessionResp::Clear() {
// @@protoc_insertion_point(message_clear_start:user.v1.CreateSessionResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.session_id_.ClearToEmpty();
  _impl_.user_id_.ClearToEmpty();
  _impl_.username_.ClearToEmpty();
  _impl_.nickname_.ClearToEmpty();
  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CreateSessionResp::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CreateSessionResp& this_ = static_cast<const CreateSessionResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CreateSessionResp::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CreateSessionResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.v1.CreateSessionResp)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string session_id = 1;
          if (!this_._internal_session_id().empty()) {
            const std::string& _s = this_._internal_session_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.CreateSessionResp.session_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string user_id = 2;
          if (!this_._internal_user_id().empty()) {
            const std::string& _s = this_._internal_user_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.CreateSessionResp.user_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string username = 3;
          if (!this_._internal_username().empty()) {
            const std::string& _s = this_._internal_username();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.CreateSessionResp.username");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // string nickname = 4;
          if (!this_._internal_nickname().empty()) {
            const std::string& _s = this_._internal_nickname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.CreateSessionResp.nickname");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string message = 16;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.CreateSessionResp.message");
            target = stream->WriteStringMaybeAliased(16, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.v1.CreateSessionResp)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CreateSessionResp::ByteSizeLong(const MessageLite& base) {
          const CreateSessionResp& this_ = static_cast<const CreateSessionResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CreateSessionResp::ByteSizeLong() const {
          const CreateSessionResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.v1.CreateSessionResp)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string session_id = 1;
            if (!this_._internal_session_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_session_id());
            }
            // string user_id = 2;
            if (!this_._internal_user_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user_id());
            }
            // string username = 3;
            if (!this_._internal_username().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_username());
            }
            // string nickname = 4;
            if (!this_._internal_nickname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_nickname());
            }
            // string message = 16;
            if (!this_._internal_message().empty()) {
              total_size += 2 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CreateSessionResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CreateSessionResp*>(&to_msg);
  auto& from = static_cast<const CreateSessionResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.v1.CreateSessionResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_session_id().empty()) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (!from._internal_username().empty()) {
    _this->_internal_set_username(from._internal_username());
  }
  if (!from._internal_nickname().empty()) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CreateSessionResp::CopyFrom(const CreateSessionResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.v1.CreateSessionResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CreateSessionResp::InternalSwap(CreateSessionResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.session_id_, &other->_impl_.session_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata CreateSessionResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateSessionReq::_Internal {
 public:
};

UpdateSessionReq::UpdateSessionReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:user.v1.UpdateSessionReq)
}
UpdateSessionReq::UpdateSessionReq(
    ::google::protobuf::Arena* arena,
    const UpdateSessionReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateSessionReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:user.v1.UpdateSessionReq)
}

inline void* UpdateSessionReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UpdateSessionReq(arena);
}
constexpr auto UpdateSessionReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UpdateSessionReq),
                                            alignof(UpdateSessionReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UpdateSessionReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UpdateSessionReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UpdateSessionReq::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<UpdateSessionReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UpdateSessionReq::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<UpdateSessionReq>(), &UpdateSessionReq::ByteSizeLong,
            &UpdateSessionReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UpdateSessionReq, _impl_._cached_size_),
        false,
    },
    &UpdateSessionReq::kDescriptorMethods,
    &descriptor_table_user_2fv1_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UpdateSessionReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> UpdateSessionReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::v1::UpdateSessionReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata UpdateSessionReq::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateSessionResp::_Internal {
 public:
};

UpdateSessionResp::UpdateSessionResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:user.v1.UpdateSessionResp)
}
UpdateSessionResp::UpdateSessionResp(
    ::google::protobuf::Arena* arena,
    const UpdateSessionResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateSessionResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:user.v1.UpdateSessionResp)
}

inline void* UpdateSessionResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UpdateSessionResp(arena);
}
constexpr auto UpdateSessionResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UpdateSessionResp),
                                            alignof(UpdateSessionResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UpdateSessionResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UpdateSessionResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UpdateSessionResp::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<UpdateSessionResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UpdateSessionResp::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<UpdateSessionResp>(), &UpdateSessionResp::ByteSizeLong,
            &UpdateSessionResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UpdateSessionResp, _impl_._cached_size_),
        false,
    },
    &UpdateSessionResp::kDescriptorMethods,
    &descriptor_table_user_2fv1_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UpdateSessionResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> UpdateSessionResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::v1::UpdateSessionResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata UpdateSessionResp::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DeleteSessionReq::_Internal {
 public:
};

DeleteSessionReq::DeleteSessionReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.v1.DeleteSessionReq)
}
inline PROTOBUF_NDEBUG_INLINE DeleteSessionReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::v1::DeleteSessionReq& from_msg)
      : session_id_(arena, from.session_id_),
        _cached_size_{0} {}

DeleteSessionReq::DeleteSessionReq(
    ::google::protobuf::Arena* arena,
    const DeleteSessionReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DeleteSessionReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:user.v1.DeleteSessionReq)
}
inline PROTOBUF_NDEBUG_INLINE DeleteSessionReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : session_id_(arena),
        _cached_size_{0} {}

inline void DeleteSessionReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DeleteSessionReq::~DeleteSessionReq() {
  // @@protoc_insertion_point(destructor:user.v1.DeleteSessionReq)
  SharedDtor(*this);
}
inline void DeleteSessionReq::SharedDtor(MessageLite& self) {
  DeleteSessionReq& this_ = static_cast<DeleteSessionReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.session_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* DeleteSessionReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DeleteSessionReq(arena);
}
constexpr auto DeleteSessionReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DeleteSessionReq),
                                            alignof(DeleteSessionReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DeleteSessionReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DeleteSessionReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DeleteSessionReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DeleteSessionReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DeleteSessionReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DeleteSessionReq>(), &DeleteSessionReq::ByteSizeLong,
            &DeleteSessionReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DeleteSessionReq, _impl_._cached_size_),
        false,
    },
    &DeleteSessionReq::kDescriptorMethods,
    &descriptor_table_user_2fv1_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DeleteSessionReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> DeleteSessionReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::v1::DeleteSessionReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string session_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DeleteSessionReq, _impl_.session_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string session_id = 1;
    {PROTOBUF_FIELD_OFFSET(DeleteSessionReq, _impl_.session_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\12\0\0\0\0\0\0"
    "user.v1.DeleteSessionReq"
    "session_id"
  }},
};

PROTOBUF_NOINLINE void DeleteSessionReq::Clear() {
// @@protoc_insertion_point(message_clear_start:user.v1.DeleteSessionReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.session_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DeleteSessionReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DeleteSessionReq& this_ = static_cast<const DeleteSessionReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DeleteSessionReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DeleteSessionReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.v1.DeleteSessionReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string session_id = 1;
          if (!this_._internal_session_id().empty()) {
            const std::string& _s = this_._internal_session_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.DeleteSessionReq.session_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.v1.DeleteSessionReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DeleteSessionReq::ByteSizeLong(const MessageLite& base) {
          const DeleteSessionReq& this_ = static_cast<const DeleteSessionReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DeleteSessionReq::ByteSizeLong() const {
          const DeleteSessionReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.v1.DeleteSessionReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string session_id = 1;
            if (!this_._internal_session_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_session_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DeleteSessionReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DeleteSessionReq*>(&to_msg);
  auto& from = static_cast<const DeleteSessionReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.v1.DeleteSessionReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_session_id().empty()) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DeleteSessionReq::CopyFrom(const DeleteSessionReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.v1.DeleteSessionReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DeleteSessionReq::InternalSwap(DeleteSessionReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.session_id_, &other->_impl_.session_id_, arena);
}

::google::protobuf::Metadata DeleteSessionReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DeleteSessionResp::_Internal {
 public:
};

DeleteSessionResp::DeleteSessionResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.v1.DeleteSessionResp)
}
inline PROTOBUF_NDEBUG_INLINE DeleteSessionResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::v1::DeleteSessionResp& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

DeleteSessionResp::DeleteSessionResp(
    ::google::protobuf::Arena* arena,
    const DeleteSessionResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DeleteSessionResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:user.v1.DeleteSessionResp)
}
inline PROTOBUF_NDEBUG_INLINE DeleteSessionResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void DeleteSessionResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DeleteSessionResp::~DeleteSessionResp() {
  // @@protoc_insertion_point(destructor:user.v1.DeleteSessionResp)
  SharedDtor(*this);
}
inline void DeleteSessionResp::SharedDtor(MessageLite& self) {
  DeleteSessionResp& this_ = static_cast<DeleteSessionResp&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* DeleteSessionResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DeleteSessionResp(arena);
}
constexpr auto DeleteSessionResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DeleteSessionResp),
                                            alignof(DeleteSessionResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DeleteSessionResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DeleteSessionResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DeleteSessionResp::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DeleteSessionResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DeleteSessionResp::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DeleteSessionResp>(), &DeleteSessionResp::ByteSizeLong,
            &DeleteSessionResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DeleteSessionResp, _impl_._cached_size_),
        false,
    },
    &DeleteSessionResp::kDescriptorMethods,
    &descriptor_table_user_2fv1_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DeleteSessionResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> DeleteSessionResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::v1::DeleteSessionResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DeleteSessionResp, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(DeleteSessionResp, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\7\0\0\0\0\0\0"
    "user.v1.DeleteSessionResp"
    "message"
  }},
};

PROTOBUF_NOINLINE void DeleteSessionResp::Clear() {
// @@protoc_insertion_point(message_clear_start:user.v1.DeleteSessionResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DeleteSessionResp::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DeleteSessionResp& this_ = static_cast<const DeleteSessionResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DeleteSessionResp::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DeleteSessionResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.v1.DeleteSessionResp)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string message = 1;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.v1.DeleteSessionResp.message");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.v1.DeleteSessionResp)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DeleteSessionResp::ByteSizeLong(const MessageLite& base) {
          const DeleteSessionResp& this_ = static_cast<const DeleteSessionResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DeleteSessionResp::ByteSizeLong() const {
          const DeleteSessionResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.v1.DeleteSessionResp)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string message = 1;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DeleteSessionResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DeleteSessionResp*>(&to_msg);
  auto& from = static_cast<const DeleteSessionResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.v1.DeleteSessionResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DeleteSessionResp::CopyFrom(const DeleteSessionResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.v1.DeleteSessionResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DeleteSessionResp::InternalSwap(DeleteSessionResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata DeleteSessionResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace user
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_user_2fv1_2fauth_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
