// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user/v1/user.proto
#ifndef GRPC_user_2fv1_2fuser_2eproto__INCLUDED
#define GRPC_user_2fv1_2fuser_2eproto__INCLUDED

#include "user/v1/user.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace user {
namespace v1 {

class UserService final {
 public:
  static constexpr char const* service_full_name() {
    return "user.v1.UserService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::user::v1::GetUserResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::GetUserResp>> AsyncGetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::GetUserResp>>(AsyncGetUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::GetUserResp>> PrepareAsyncGetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::GetUserResp>>(PrepareAsyncGetUserRaw(context, request, cq));
    }
    // 获取用户信息
    virtual ::grpc::Status CreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::user::v1::CreateUserResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateUserResp>> AsyncCreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateUserResp>>(AsyncCreateUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateUserResp>> PrepareAsyncCreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateUserResp>>(PrepareAsyncCreateUserRaw(context, request, cq));
    }
    // 创建用户
    virtual ::grpc::Status ListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::user::v1::ListUsernamesResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsernamesResp>> AsyncListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsernamesResp>>(AsyncListUsernamesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsernamesResp>> PrepareAsyncListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsernamesResp>>(PrepareAsyncListUsernamesRaw(context, request, cq));
    }
    // 列出所有username
    virtual ::grpc::Status ListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::user::v1::ListUsersResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsersResp>> AsyncListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsersResp>>(AsyncListUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsersResp>> PrepareAsyncListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsersResp>>(PrepareAsyncListUsersRaw(context, request, cq));
    }
    // 获取用户列表（带分页）
    virtual ::grpc::Status UpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::user::v1::UpdateUserResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateUserResp>> AsyncUpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateUserResp>>(AsyncUpdateUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateUserResp>> PrepareAsyncUpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateUserResp>>(PrepareAsyncUpdateUserRaw(context, request, cq));
    }
    // 更新用户信息
    virtual ::grpc::Status UpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::user::v1::UpdateMainKeyResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateMainKeyResp>> AsyncUpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateMainKeyResp>>(AsyncUpdateMainKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateMainKeyResp>> PrepareAsyncUpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateMainKeyResp>>(PrepareAsyncUpdateMainKeyRaw(context, request, cq));
    }
    // 更新用户密码
    virtual ::grpc::Status DeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncDeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncDeleteUserRaw(context, request, cq));
    }
    // 删除用户
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq* request, ::user::v1::GetUserResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq* request, ::user::v1::GetUserResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取用户信息
      virtual void CreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq* request, ::user::v1::CreateUserResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq* request, ::user::v1::CreateUserResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 创建用户
      virtual void ListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq* request, ::user::v1::ListUsernamesResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq* request, ::user::v1::ListUsernamesResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 列出所有username
      virtual void ListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq* request, ::user::v1::ListUsersResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq* request, ::user::v1::ListUsersResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取用户列表（带分页）
      virtual void UpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq* request, ::user::v1::UpdateUserResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq* request, ::user::v1::UpdateUserResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 更新用户信息
      virtual void UpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq* request, ::user::v1::UpdateMainKeyResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq* request, ::user::v1::UpdateMainKeyResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 更新用户密码
      virtual void DeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 删除用户
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::GetUserResp>* AsyncGetUserRaw(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::GetUserResp>* PrepareAsyncGetUserRaw(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateUserResp>* AsyncCreateUserRaw(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::CreateUserResp>* PrepareAsyncCreateUserRaw(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsernamesResp>* AsyncListUsernamesRaw(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsernamesResp>* PrepareAsyncListUsernamesRaw(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsersResp>* AsyncListUsersRaw(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::ListUsersResp>* PrepareAsyncListUsersRaw(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateUserResp>* AsyncUpdateUserRaw(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateUserResp>* PrepareAsyncUpdateUserRaw(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateMainKeyResp>* AsyncUpdateMainKeyRaw(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::v1::UpdateMainKeyResp>* PrepareAsyncUpdateMainKeyRaw(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteUserRaw(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncDeleteUserRaw(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::user::v1::GetUserResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::GetUserResp>> AsyncGetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::GetUserResp>>(AsyncGetUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::GetUserResp>> PrepareAsyncGetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::GetUserResp>>(PrepareAsyncGetUserRaw(context, request, cq));
    }
    ::grpc::Status CreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::user::v1::CreateUserResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::CreateUserResp>> AsyncCreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::CreateUserResp>>(AsyncCreateUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::CreateUserResp>> PrepareAsyncCreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::CreateUserResp>>(PrepareAsyncCreateUserRaw(context, request, cq));
    }
    ::grpc::Status ListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::user::v1::ListUsernamesResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsernamesResp>> AsyncListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsernamesResp>>(AsyncListUsernamesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsernamesResp>> PrepareAsyncListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsernamesResp>>(PrepareAsyncListUsernamesRaw(context, request, cq));
    }
    ::grpc::Status ListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::user::v1::ListUsersResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsersResp>> AsyncListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsersResp>>(AsyncListUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsersResp>> PrepareAsyncListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsersResp>>(PrepareAsyncListUsersRaw(context, request, cq));
    }
    ::grpc::Status UpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::user::v1::UpdateUserResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateUserResp>> AsyncUpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateUserResp>>(AsyncUpdateUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateUserResp>> PrepareAsyncUpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateUserResp>>(PrepareAsyncUpdateUserRaw(context, request, cq));
    }
    ::grpc::Status UpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::user::v1::UpdateMainKeyResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateMainKeyResp>> AsyncUpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateMainKeyResp>>(AsyncUpdateMainKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateMainKeyResp>> PrepareAsyncUpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateMainKeyResp>>(PrepareAsyncUpdateMainKeyRaw(context, request, cq));
    }
    ::grpc::Status DeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncDeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncDeleteUserRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq* request, ::user::v1::GetUserResp* response, std::function<void(::grpc::Status)>) override;
      void GetUser(::grpc::ClientContext* context, const ::user::v1::GetUserReq* request, ::user::v1::GetUserResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq* request, ::user::v1::CreateUserResp* response, std::function<void(::grpc::Status)>) override;
      void CreateUser(::grpc::ClientContext* context, const ::user::v1::CreateUserReq* request, ::user::v1::CreateUserResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq* request, ::user::v1::ListUsernamesResp* response, std::function<void(::grpc::Status)>) override;
      void ListUsernames(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq* request, ::user::v1::ListUsernamesResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq* request, ::user::v1::ListUsersResp* response, std::function<void(::grpc::Status)>) override;
      void ListUsers(::grpc::ClientContext* context, const ::user::v1::ListUsersReq* request, ::user::v1::ListUsersResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq* request, ::user::v1::UpdateUserResp* response, std::function<void(::grpc::Status)>) override;
      void UpdateUser(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq* request, ::user::v1::UpdateUserResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq* request, ::user::v1::UpdateMainKeyResp* response, std::function<void(::grpc::Status)>) override;
      void UpdateMainKey(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq* request, ::user::v1::UpdateMainKeyResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void DeleteUser(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::user::v1::GetUserResp>* AsyncGetUserRaw(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::GetUserResp>* PrepareAsyncGetUserRaw(::grpc::ClientContext* context, const ::user::v1::GetUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::CreateUserResp>* AsyncCreateUserRaw(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::CreateUserResp>* PrepareAsyncCreateUserRaw(::grpc::ClientContext* context, const ::user::v1::CreateUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsernamesResp>* AsyncListUsernamesRaw(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsernamesResp>* PrepareAsyncListUsernamesRaw(::grpc::ClientContext* context, const ::user::v1::ListUsernamesReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsersResp>* AsyncListUsersRaw(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::ListUsersResp>* PrepareAsyncListUsersRaw(::grpc::ClientContext* context, const ::user::v1::ListUsersReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateUserResp>* AsyncUpdateUserRaw(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateUserResp>* PrepareAsyncUpdateUserRaw(::grpc::ClientContext* context, const ::user::v1::UpdateUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateMainKeyResp>* AsyncUpdateMainKeyRaw(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::v1::UpdateMainKeyResp>* PrepareAsyncUpdateMainKeyRaw(::grpc::ClientContext* context, const ::user::v1::UpdateMainKeyReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteUserRaw(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncDeleteUserRaw(::grpc::ClientContext* context, const ::user::v1::DeleteUserReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetUser_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateUser_;
    const ::grpc::internal::RpcMethod rpcmethod_ListUsernames_;
    const ::grpc::internal::RpcMethod rpcmethod_ListUsers_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateUser_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateMainKey_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteUser_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetUser(::grpc::ServerContext* context, const ::user::v1::GetUserReq* request, ::user::v1::GetUserResp* response);
    // 获取用户信息
    virtual ::grpc::Status CreateUser(::grpc::ServerContext* context, const ::user::v1::CreateUserReq* request, ::user::v1::CreateUserResp* response);
    // 创建用户
    virtual ::grpc::Status ListUsernames(::grpc::ServerContext* context, const ::user::v1::ListUsernamesReq* request, ::user::v1::ListUsernamesResp* response);
    // 列出所有username
    virtual ::grpc::Status ListUsers(::grpc::ServerContext* context, const ::user::v1::ListUsersReq* request, ::user::v1::ListUsersResp* response);
    // 获取用户列表（带分页）
    virtual ::grpc::Status UpdateUser(::grpc::ServerContext* context, const ::user::v1::UpdateUserReq* request, ::user::v1::UpdateUserResp* response);
    // 更新用户信息
    virtual ::grpc::Status UpdateMainKey(::grpc::ServerContext* context, const ::user::v1::UpdateMainKeyReq* request, ::user::v1::UpdateMainKeyResp* response);
    // 更新用户密码
    virtual ::grpc::Status DeleteUser(::grpc::ServerContext* context, const ::user::v1::DeleteUserReq* request, ::google::protobuf::Empty* response);
    // 删除用户
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUser() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::user::v1::GetUserReq* /*request*/, ::user::v1::GetUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUser(::grpc::ServerContext* context, ::user::v1::GetUserReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::GetUserResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateUser() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CreateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateUser(::grpc::ServerContext* /*context*/, const ::user::v1::CreateUserReq* /*request*/, ::user::v1::CreateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateUser(::grpc::ServerContext* context, ::user::v1::CreateUserReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::CreateUserResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListUsernames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListUsernames() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ListUsernames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsernames(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsernamesReq* /*request*/, ::user::v1::ListUsernamesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListUsernames(::grpc::ServerContext* context, ::user::v1::ListUsernamesReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::ListUsernamesResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListUsers() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ListUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsers(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsersReq* /*request*/, ::user::v1::ListUsersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListUsers(::grpc::ServerContext* context, ::user::v1::ListUsersReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::ListUsersResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateUser() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_UpdateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUser(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateUserReq* /*request*/, ::user::v1::UpdateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateUser(::grpc::ServerContext* context, ::user::v1::UpdateUserReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::UpdateUserResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateMainKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateMainKey() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_UpdateMainKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMainKey(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateMainKeyReq* /*request*/, ::user::v1::UpdateMainKeyResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateMainKey(::grpc::ServerContext* context, ::user::v1::UpdateMainKeyReq* request, ::grpc::ServerAsyncResponseWriter< ::user::v1::UpdateMainKeyResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteUser() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_DeleteUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteUser(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteUserReq* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteUser(::grpc::ServerContext* context, ::user::v1::DeleteUserReq* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetUser<WithAsyncMethod_CreateUser<WithAsyncMethod_ListUsernames<WithAsyncMethod_ListUsers<WithAsyncMethod_UpdateUser<WithAsyncMethod_UpdateMainKey<WithAsyncMethod_DeleteUser<Service > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUser() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::GetUserReq, ::user::v1::GetUserResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::GetUserReq* request, ::user::v1::GetUserResp* response) { return this->GetUser(context, request, response); }));}
    void SetMessageAllocatorFor_GetUser(
        ::grpc::MessageAllocator< ::user::v1::GetUserReq, ::user::v1::GetUserResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::GetUserReq, ::user::v1::GetUserResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::user::v1::GetUserReq* /*request*/, ::user::v1::GetUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUser(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::GetUserReq* /*request*/, ::user::v1::GetUserResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CreateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateUser() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::CreateUserReq, ::user::v1::CreateUserResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::CreateUserReq* request, ::user::v1::CreateUserResp* response) { return this->CreateUser(context, request, response); }));}
    void SetMessageAllocatorFor_CreateUser(
        ::grpc::MessageAllocator< ::user::v1::CreateUserReq, ::user::v1::CreateUserResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::CreateUserReq, ::user::v1::CreateUserResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateUser(::grpc::ServerContext* /*context*/, const ::user::v1::CreateUserReq* /*request*/, ::user::v1::CreateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateUser(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::CreateUserReq* /*request*/, ::user::v1::CreateUserResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListUsernames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListUsernames() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::ListUsernamesReq, ::user::v1::ListUsernamesResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::ListUsernamesReq* request, ::user::v1::ListUsernamesResp* response) { return this->ListUsernames(context, request, response); }));}
    void SetMessageAllocatorFor_ListUsernames(
        ::grpc::MessageAllocator< ::user::v1::ListUsernamesReq, ::user::v1::ListUsernamesResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::ListUsernamesReq, ::user::v1::ListUsernamesResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListUsernames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsernames(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsernamesReq* /*request*/, ::user::v1::ListUsernamesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListUsernames(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::ListUsernamesReq* /*request*/, ::user::v1::ListUsernamesResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListUsers() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::ListUsersReq, ::user::v1::ListUsersResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::ListUsersReq* request, ::user::v1::ListUsersResp* response) { return this->ListUsers(context, request, response); }));}
    void SetMessageAllocatorFor_ListUsers(
        ::grpc::MessageAllocator< ::user::v1::ListUsersReq, ::user::v1::ListUsersResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::ListUsersReq, ::user::v1::ListUsersResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsers(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsersReq* /*request*/, ::user::v1::ListUsersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::ListUsersReq* /*request*/, ::user::v1::ListUsersResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateUser() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::UpdateUserReq, ::user::v1::UpdateUserResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::UpdateUserReq* request, ::user::v1::UpdateUserResp* response) { return this->UpdateUser(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateUser(
        ::grpc::MessageAllocator< ::user::v1::UpdateUserReq, ::user::v1::UpdateUserResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::UpdateUserReq, ::user::v1::UpdateUserResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUser(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateUserReq* /*request*/, ::user::v1::UpdateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateUser(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::UpdateUserReq* /*request*/, ::user::v1::UpdateUserResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateMainKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateMainKey() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::UpdateMainKeyReq, ::user::v1::UpdateMainKeyResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::UpdateMainKeyReq* request, ::user::v1::UpdateMainKeyResp* response) { return this->UpdateMainKey(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateMainKey(
        ::grpc::MessageAllocator< ::user::v1::UpdateMainKeyReq, ::user::v1::UpdateMainKeyResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::UpdateMainKeyReq, ::user::v1::UpdateMainKeyResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateMainKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMainKey(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateMainKeyReq* /*request*/, ::user::v1::UpdateMainKeyResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateMainKey(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::UpdateMainKeyReq* /*request*/, ::user::v1::UpdateMainKeyResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteUser() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::user::v1::DeleteUserReq, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::v1::DeleteUserReq* request, ::google::protobuf::Empty* response) { return this->DeleteUser(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteUser(
        ::grpc::MessageAllocator< ::user::v1::DeleteUserReq, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::v1::DeleteUserReq, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteUser(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteUserReq* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteUser(
      ::grpc::CallbackServerContext* /*context*/, const ::user::v1::DeleteUserReq* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetUser<WithCallbackMethod_CreateUser<WithCallbackMethod_ListUsernames<WithCallbackMethod_ListUsers<WithCallbackMethod_UpdateUser<WithCallbackMethod_UpdateMainKey<WithCallbackMethod_DeleteUser<Service > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUser() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::user::v1::GetUserReq* /*request*/, ::user::v1::GetUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateUser() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CreateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateUser(::grpc::ServerContext* /*context*/, const ::user::v1::CreateUserReq* /*request*/, ::user::v1::CreateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListUsernames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListUsernames() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ListUsernames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsernames(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsernamesReq* /*request*/, ::user::v1::ListUsernamesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListUsers() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ListUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsers(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsersReq* /*request*/, ::user::v1::ListUsersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateUser() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_UpdateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUser(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateUserReq* /*request*/, ::user::v1::UpdateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateMainKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateMainKey() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_UpdateMainKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMainKey(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateMainKeyReq* /*request*/, ::user::v1::UpdateMainKeyResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteUser() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_DeleteUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteUser(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteUserReq* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUser() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::user::v1::GetUserReq* /*request*/, ::user::v1::GetUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateUser() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CreateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateUser(::grpc::ServerContext* /*context*/, const ::user::v1::CreateUserReq* /*request*/, ::user::v1::CreateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListUsernames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListUsernames() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ListUsernames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsernames(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsernamesReq* /*request*/, ::user::v1::ListUsernamesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListUsernames(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListUsers() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ListUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsers(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsersReq* /*request*/, ::user::v1::ListUsersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListUsers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateUser() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_UpdateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUser(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateUserReq* /*request*/, ::user::v1::UpdateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateMainKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateMainKey() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_UpdateMainKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMainKey(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateMainKeyReq* /*request*/, ::user::v1::UpdateMainKeyResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateMainKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteUser() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_DeleteUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteUser(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteUserReq* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUser() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::user::v1::GetUserReq* /*request*/, ::user::v1::GetUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateUser() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateUser(::grpc::ServerContext* /*context*/, const ::user::v1::CreateUserReq* /*request*/, ::user::v1::CreateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListUsernames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListUsernames() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListUsernames(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListUsernames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsernames(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsernamesReq* /*request*/, ::user::v1::ListUsernamesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListUsernames(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListUsers() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListUsers(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListUsers(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsersReq* /*request*/, ::user::v1::ListUsersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateUser() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateUser(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateUserReq* /*request*/, ::user::v1::UpdateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateMainKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateMainKey() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateMainKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateMainKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMainKey(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateMainKeyReq* /*request*/, ::user::v1::UpdateMainKeyResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateMainKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteUser() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteUser(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteUserReq* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUser() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::GetUserReq, ::user::v1::GetUserResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::GetUserReq, ::user::v1::GetUserResp>* streamer) {
                       return this->StreamedGetUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUser(::grpc::ServerContext* /*context*/, const ::user::v1::GetUserReq* /*request*/, ::user::v1::GetUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::GetUserReq,::user::v1::GetUserResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateUser() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::CreateUserReq, ::user::v1::CreateUserResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::CreateUserReq, ::user::v1::CreateUserResp>* streamer) {
                       return this->StreamedCreateUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateUser(::grpc::ServerContext* /*context*/, const ::user::v1::CreateUserReq* /*request*/, ::user::v1::CreateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::CreateUserReq,::user::v1::CreateUserResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListUsernames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListUsernames() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::ListUsernamesReq, ::user::v1::ListUsernamesResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::ListUsernamesReq, ::user::v1::ListUsernamesResp>* streamer) {
                       return this->StreamedListUsernames(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListUsernames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListUsernames(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsernamesReq* /*request*/, ::user::v1::ListUsernamesResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListUsernames(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::ListUsernamesReq,::user::v1::ListUsernamesResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListUsers() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::ListUsersReq, ::user::v1::ListUsersResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::ListUsersReq, ::user::v1::ListUsersResp>* streamer) {
                       return this->StreamedListUsers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListUsers(::grpc::ServerContext* /*context*/, const ::user::v1::ListUsersReq* /*request*/, ::user::v1::ListUsersResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListUsers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::ListUsersReq,::user::v1::ListUsersResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateUser() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::UpdateUserReq, ::user::v1::UpdateUserResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::UpdateUserReq, ::user::v1::UpdateUserResp>* streamer) {
                       return this->StreamedUpdateUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateUser(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateUserReq* /*request*/, ::user::v1::UpdateUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::UpdateUserReq,::user::v1::UpdateUserResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateMainKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateMainKey() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::UpdateMainKeyReq, ::user::v1::UpdateMainKeyResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::UpdateMainKeyReq, ::user::v1::UpdateMainKeyResp>* streamer) {
                       return this->StreamedUpdateMainKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateMainKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateMainKey(::grpc::ServerContext* /*context*/, const ::user::v1::UpdateMainKeyReq* /*request*/, ::user::v1::UpdateMainKeyResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateMainKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::UpdateMainKeyReq,::user::v1::UpdateMainKeyResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteUser() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::v1::DeleteUserReq, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::v1::DeleteUserReq, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedDeleteUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteUser(::grpc::ServerContext* /*context*/, const ::user::v1::DeleteUserReq* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::v1::DeleteUserReq,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetUser<WithStreamedUnaryMethod_CreateUser<WithStreamedUnaryMethod_ListUsernames<WithStreamedUnaryMethod_ListUsers<WithStreamedUnaryMethod_UpdateUser<WithStreamedUnaryMethod_UpdateMainKey<WithStreamedUnaryMethod_DeleteUser<Service > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetUser<WithStreamedUnaryMethod_CreateUser<WithStreamedUnaryMethod_ListUsernames<WithStreamedUnaryMethod_ListUsers<WithStreamedUnaryMethod_UpdateUser<WithStreamedUnaryMethod_UpdateMainKey<WithStreamedUnaryMethod_DeleteUser<Service > > > > > > > StreamedService;
};

}  // namespace v1
}  // namespace user


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_user_2fv1_2fuser_2eproto__INCLUDED
